### ISSUE TITLE
Add The Repository resource on Jakarta Data

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#1]
As an initial step of Jakarta Data, where the mission is to provide easy-to-use data access technologies, we can add initial interfaces and interfaces.

**Description**

As a:

API user (application developer)

...I need to be able to:

I would propose to submit the repository approach based on those classes:

...which enables me to:

* `Repository` based on [Spring Data CrudRepository](https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/repository/CrudRepository.java)
* `Entity` annotation also see #3 because it may sound ambiguous to have multiple such annotations at least in this spec
* `Id` annotation

Other annotations belong to the implementation, e.g., JPA has relation annotation, JAR-RS might use [JSON-B](https://javaee.github.io/jsonb-spec/) annotations, and NoSQL with Jakarta NoSQL.

## Tasks

- [ ] [Name convention](https://github.com/jakartaee/data-api/issues/6)

**Comment by keilw** [comment]
Those should be based on [Repository](https://github.com/eclipse-ee4j/nosql/blob/main/api/mapping/mapping-core/src/main/java/jakarta/nosql/mapping/Repository.java)
and other elements in the Jakarta NoSQL repository.
The same element in Spring Data is a complete no-op or pure tagging interface, so if we really wanted to make such  difference or have a "Read Only" repository as opposed to a "CRUD" one, then it seems more reasonable to leave the `find*`, `exists` and `count` methods in a `Repository` interface, while something like `MutableRepository` or `CrudRepository` could extend that one.

**Comment by otaviojava** [comment]
We'll close to keep the issue on one place: https://github.com/jakartaee/data-api/issues/3

**Comment by keilw** [comment]
@otaviojava Actually this was the umbrella, but maybe just create a new ticket for the Repository pattern, etc.
