### ISSUE TITLE
The Between keyword is misleading

### ISSUE THREAD

**Issue by njr-11** [jakartaee/data#111]
While giving a presentation on Jakarta Data to other developers, some gave feedback that the `Between` keyword is wrongly named when the range is inclusive of the first and last number specified, rather than following the true meaning of the word "between" which would be exclusive. One attendee even went so far as to follow up afterward with links, such as https://en.wikipedia.org/wiki/Interval_(mathematics) , which contain language from the mathematical perspective demonstrating the word "between" being used correctly, like this,

```
the set of numbers x satisfying 0 <= x <= 1 is an interval which contains 0, 1, and all numbers in between.
```

and https://www.cuemath.com/algebra/interval-notation/ ,

```
an interval expressed as 1 < x < 5 denotes a set of numbers lying between 1 and 5.
```

The language in the above show the word "between" being used with its literal meaning, in contrast to the imprecise meaning of BETWEEN that is used by [Jakarta Persistence/JPQL](https://jakarta.ee/specifications/persistence/3.1/jakarta-persistence-spec-3.1.html#between-expressions), which states,

```
p.age BETWEEN 15 and 19 is equivalent to p.age >= 15 AND p.age <= 19
```

I'm not sure what the best course of action is here.
One option would be to replace the `Between` keyword with a `Within` keyword, which would more accurately correspond to the behavior that you are getting. That is what I would advocate for if this were being designed for the first time, to avoid the confusion. [Spring Data](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#appendix.query.method.predicate) actually already has a `Within` keyword, but other implementations don't. The `Between` keyword seems to be common across existing implementations. I'm curious what thoughts other have on this. Is it confusing enough to be worth switching to `Within`? Or is it best left as is?

**Comment by mp911de** [comment]
`Between` is only precise if the underlying implementation can construct a store-native between predicate. Stores like Mongo, that do not have a `Between` operator are required to make them most sense out of the keyword. Specifically, Spring Data MongoDB uses greater (gt) and less (lt) operators (not gte/lte) to assemble a between query.

The alternative usage can be seen with a `Range` object that specifies bound inclusion/exclusion.
