### ISSUE TITLE
Should we have the Entity and Id annotation at Data spec?

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#112]
This issue follows the same step of [Sort annotation](https://github.com/jakartaee/data/issues/94).

Should we have the Entity and ID annotations?

I'd like to know if a JPA user will replace the JPA annotation to use Jakarta Data instead, and IMHO: defining mapping Entity/database is beyond the spec scope.

**Comment by mp911de** [comment]
Consider the following code snippet:

```java
@jakarta.data.Entity
@jakarta.persistence.Entity
class {
  
  @jakarta.data.Id
  @jakarta.persistence.Id
  Long id;
}
```

In short: No.

Each repository implementation should have means to determine the identifier property and whether a given class is an entity of the respective implementation module.

**Comment by njr-11** [comment]
I agree with removing these. Relational database users will not be interested in `jakarta.data.Entity`. They will want to use `jakarta.persistence.Entity` and corresponding annotations from Jakarta Persistence which they are already familiar with and which have a much richer feature set. Annotations in `jakarta.persistence` will be maintained and evolved over time by the Jakarta Persistence specification, and any duplication of that would inevitably become out of sync.

Entity annotations for Jakarta NoSQL can be owned and maintained within the Jakarta NoSQL specification. This will make for a very natural model where users of relational databases can use the entity annotations from Jakarta Persistence and users of NoSQL can use the entity annotations from the Jakarta NoSQL specifications, with each type of entity annotation owned and maintained by the respective specification.
