### ISSUE TITLE
Need a TCK strategy to deal with eventual consistency in NoSQL databases

### ISSUE THREAD

**Issue by njr-11** [jakartaee/data#136]
I don't have a good answer for this, so I'm going to write up what I can think of. Maybe others will be able to improve on it or be able to come up with better approaches.

1. As much as reasonably possible, isolate TCK tests that require updates from those that can be achieved with just reads.
2. Have a pre-population phase that inserts the data for the latter, which is then considered the read-only data by the TCK, before running tests.
3. Introduce an `EVENTUAL_CONSISTENCY_DELAY` TCK configuration option that can be configured when running against a database with eventual consistency.
4. For tests that perform updates (and for the pre-population step), and if a `EVENTUAL_CONSISTENCY_DELAY` is specified, then after performing a group of updates, the TCK must first poll the database for an updated result to appear, and after seeing it, must sleep for the full amount of the `EVENTUAL_CONSISTENCY_DELAY` before querying again and making assertions on the state of the data.

With this approach, it will always be possible, although hopefully unlikely, for tests to fail because the TCK did not wait long enough for eventual consistency.  If this happens, the tester can react to this by increasing the delay and/or re-running the TCK.

**Comment by KyleAure** [comment]
Sorry have to re-open this issue.  I still need to create an example of waiting for eventual consistency in non-read-only repositories.

**Comment by otaviojava** [comment]
Thank you @KyleAure I closed by mistake.
