### ISSUE TITLE
Query annotation for repository methods

### ISSUE THREAD

**Issue by njr-11** [jakartaee/data#14]
**Description**

As a:

- [ ] Application user/user of the configuration itself
- [x] API user (application developer)
- [ ] SPI user (container or runtime developer)
- [ ] Specification implementer

...I need to be able to:

supply my own Jakarta NoSQL Text Queries and/or JPQL queries for repository methods

...which enables me to:

include operations that cannot be represented by method name pattern-based repository methods.

Existing solutions such as [Spring Data](https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/Query.html), [Micronaut](https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/annotation/Query.html), [Apache Delta Spike](https://deltaspike.apache.org/javadoc/1.8.0/org/apache/deltaspike/data/api/Query.html), and [Jakarta NoSQL](http://www.jnosql.org/javadoc/jakarta/nosql/mapping/Query.html) all have a `@Query` annotation that allow you to specify your own query for a repository method, which helps to cover types of queries that aren't representable with name pattern-based repository methods.

For example,

```
@Query("SELECT t FROM Task t WHERE t.ended - t.started > ?1")
List<Task> endedAfter(long time);
```

Jakarta Data would not define the query language and would instead specify that the corresponding query language and syntax that is supported by the data access provider is to be used, so Jakarta NoSQL Text Queries for Jakarta NoSQL, JPQL queries for Jakarta Persistence-based.

Some of the existing implementations have a variety of other attributes on the `@Query` annotation, but we could at least start out with the `value` attribute which seems to be pretty standard.

[Spring Data](https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/repository/query/Param.java) and [Jakarta NoSQL](http://www.jnosql.org/javadoc/jakarta/nosql/mapping/Param.html) also include an `@Param` annotation to be optionally used along with `@Query` to cover named method parameters.  We could consider including that for implementations that don't process annotations at compile time where the method parameter names are still available and usable for that purpose.  It would look something like the following (although I'm writing in JPQL because that's what the previous example was)

```
@Query("SELECT t FROM Task t WHERE t.ended - t.started > :min")
List<Task> endedAfter(@Param("min") long time);
```

**Comment by otaviojava** [comment]
@njr-11 about the Param annotation, It belongs to Spring Data:


https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/repository/query/Param.java

**Comment by keilw** [comment]
If Spring Data is the only implementation, why not leave it to such implementation?

The JavaDoc says it's "Annotation to bind method parameters to a query via a named parameter." So why not use the `@Named` annotation that already exists in Jakarta Inject?

**Comment by njr-11** [comment]
> @njr-11 about the Param annotation, It also belongs to Spring Data. I mean they were the first one to do it:
> 
> https://github.com/spring-projects/spring-data-commons/blob/main/src/main/java/org/springframework/data/repository/query/Param.java

@otaviojava Thanks for posting the link to Spring's `Param` annotation.  For some reason I wasn't able to find it when writing up the issue.  I'll get it added to the original description.



> The JavaDoc says it's "Annotation to bind method parameters to a query via a named parameter." So why not use the `@Named` annotation that already exists in Jakarta Inject?

@keilw thanks for bringing up this idea.  [@Named](https://jakarta.ee/specifications/platform/10/apidocs/jakarta/inject/named) does provide exactly what we are looking for with it being a simple annotation with just the name value and a meaningful name of its own that would make sense for named parameters.  The only disadvantage that I'm aware of is that `@Named` is also a Qualifier and the named parameters pattern isn't using it as a Qualifier.  I'd be curious what others think about this idea.
