### ISSUE TITLE
Do we support an extra interface?

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#148]
Hello everyone, today I had a presentation about Jakarta Data, and I got a good question that I had yet to learn.

What is the expected behavior in this situation?

As a user, given I have multiple commons queries on the repository, I decided to put it on an interface.

```java
public interface BaseQueriesFromUser<T> {

    List<T> findByName(String name);

    List<T> findByYear(String name);
}
```

So, I'll put this one in multiple repositories:

```java
@Repository
public interface Library extends CrudRepository<Book, String>, BaseQueriesFromUser<Book> {
}

@Repository
public interface Airport extends CrudRepository<AirPlane, String>, BaseQueriesFromUser<AirPlane> {
}

```

What is the expected behavior from the spec?

I did not find anything like that before.

I checked, and it already works on JNoSQL, and I did not test it.

**Comment by njr-11** [comment]
The spec doesn't currently say anything about this scenario one way or the other, but it seems like a reasonable thing to be able to do, so I'd be fine with it being added if the vendors are okay with it.

**Comment by mp911de** [comment]
It is a neat approach to include customizations. Spring Data uses a concept of fragments to be able to compose a repository from potentially multiple implementations. This turns effectively the default implementation (which implements the actual `CrudRepository`) into a fragment as well.

**Comment by KyleAure** [comment]
I ran into this same question when working on the TCK framework: 
https://github.com/jakartaee/data/blob/4475edf9c246b6b4d643cb63b6e5871a47af2c2a/tck/src/main/java/ee/jakarta/tck/data/framework/read/only/ReadOnlyRepository.java#L23-L27

Where I wanted to limit a repository to be read-only. 
Would be a great addition!

**Comment by georgleber** [comment]
@otaviojava 
For JNoSQL this works only for repository interfaces, that use a generic type corresponding to the (like `BaseQuery<Person>`) otherwise it is ignored. 
Why not allow any "custom" repository and the user can decide to use generics or not. 

_(This might be JNoSQL specific, but could be a topic for the Data spec)_

**Comment by otaviojava** [comment]
Hey @georgleber could you open this issue on the JNoSQL repository?
So we can go deeper into it.
