### ISSUE TITLE
Explore Specializations on Repositories

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#156]
As we talked about [on this issue here](https://github.com/jakartaee/data/pull/146#issuecomment-1535740767), I would like to allow the spec to have in-depth details and expected behaviors on JPA; at the same point, don't assume that all database work as a relational database or have thousands of if exceptions at a single repository.

I propose creating a new specialization, a JPARepository, where we can do deep on behaviors for JPA.

Where: 

* DataRepository: The parent repository interface
* CrudRepository: Interface for generic CRUD operations on a repository for a specific type; thus, it should work with *any* database engine, such as SQL, NoSQL, web services, etc.
* PageableRepository: A CrudRepository specialization that works with pagination.
* JPARepository: A PageableRepository specialization that has a tight coupling with JPA, where we can define JTA, relational optimistic locking, JPA annotation, etc.

```mermaid
graph TD;
    DataRepository-->CrudRepository;
    CrudRepository-->PageableRepository;
    PageableRepository-->JPARepository;
```

On this refactoring, there is no impact at the code level, but on documentation, where we need to move those particular relational details to a single place: JPARepository.

It does not mean that a JPA user cannot use a PageableRepository; a user can inject PageableRepository, and it will work. It is the Worker analogy, A lawyer is a worker, but I should not assume that all workers need a law degree.

```java
@Inject
 PageableRepository repository; //can be a JPARepository implementation.
```

References:

* [Spring](https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html)
* [Micronaut](https://micronaut-projects.github.io/micronaut-data/1.0.0/api/io/micronaut/data/jpa/repository/JpaRepository.html)
* [EntityRepository](https://deltaspike.apache.org/javadoc/1.7.2/org/apache/deltaspike/data/api/EntityRepository.html)

:warning: I open for any name for this JPARepository.

**Comment by tandraschko** [comment]
I just wondering: should it even be "JPA" anymore? 
Same like JSF, its now just Jakarta Faces.

**Comment by KyleAure** [comment]
Correct, JPA is an Oracle copyright.  
I also don't see the benefit of defining a Jakarta Persistence exclusive repository pattern in the Jakarta Data specification. The only thing this would accomplish would be to cause confusion and make it so users assume they can only use Persistence Entities with this bespoke repository when they can use it with any of the repository interfaces.
