### ISSUE TITLE
Could OrderBy be better specified annotatively?

### ISSUE THREAD

**Issue by njr-11** [jakartaee/data#18]
**Description**

As a:

- [ ] Application user/user of the configuration itself
- [x] API user (application developer)
- [ ] SPI user (container or runtime developer)
- [ ] Specification implementer

...I need to be able to:

have a less lengthy and less error-prone way of defining custom repository methods

...which enables me to:

better understand the code that uses my repository methods and
reduce the opportunity for misspellings and mistakes in my repository methods.

Instead of writing queries such as the following that make the code almost unreadable,

```
List<Employee> findByDepartmentAndIdNotOrderByPositionDescLastNameAscFirstNameAsc(String deptNum, int empNum);

...
coworkers = employees.findByDepartmentAndIdNotOrderByPositionDescLastNameAscFirstNameAsc(deptNum, empNum);
```

suppose we allowed the sorting information to all be declared annotatively,

```
@OrderBy(value = "position", descending = true)
@OrderBy("lastName")
@OrderBy("firstName")
List<Employee> findByDepartmentAndIdNot(String deptNum, int empNum);

...
coworkers = employees.findByDepartmentAndIdNot(deptNum, empNum);
```

The only disadvantage I can think of is if someone wanted to duplicate the exact same query but with different ordering, but it's likely that special case would already be solved by the Sorts parameter that some of the implementations have.

**Comment by otaviojava** [comment]
For a more dynamic sort option, the vendors use a parameter.

## Spring
Spring: they have a [Pageable](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Pageable.html)

```java
Pageable sortedByName =  PageRequest.of(0, 3, Sort.by("name"));
```
On the interface method:

```java
List<Product> findAllByPrice(double price, Pageable pageable);
```

## Micronaut

It has a similar approach:
[Pageable](https://micronaut-projects.github.io/micronaut-data/1.1.2/api/io/micronaut/data/model/Pageable.html)

```java
Pageable sortedByName =  PageRequest.of(0, 3, Sort.by("name"));
```

## Jakarta NoSQL

It has a [Sorts](https://www.jnosql.org/javadoc/jakarta/nosql/mapping/Sorts.html)

```java
Sorts sorts = Sorts.sorts().asc("name").desc("age");
```

```java
List<Product> findAllByPrice(double price, Sorts sorts);
```
