### ISSUE TITLE
Why does this repository have "api" in its name?

### ISSUE THREAD

**Issue by keilw** [jakartaee/data#2]
All other "spec/API" repos here are just called "security", "servlet", etc. so why was an "-api" added to this one?

**Comment by keilw** [comment]
IMO if we have a separate "spec" repository like [validation-spec](https://github.com/jakartaee/validation-spec), then calling this "data-api" sounds best, but if it was a combination of "api" and "spec" then this still totally empty repository may better be called just "data".

**Comment by arjantijms** [comment]
To be consistent with the other repos, please consider calling this "data" indeed. Even validation is called validation and not validation-api. See https://github.com/jakartaee/validation

**Comment by otaviojava** [comment]
Hello @keilw and @arjantijms, as we discussed in Today's meeting.
I've fired the issue to rename it: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1910

**Comment by keilw** [comment]
This seems fixed because it was renamed.
