### ISSUE TITLE
Obtaining the EntityManager (or NoSQL equivalents) for a repository

### ISSUE THREAD

**Issue by njr-11** [jakartaee/data#202]
The following pattern was discussed/proposed in the Jakarta Data Meeting on August 2nd:

```
@MyQualifier
@PersistenceContext(unitName = "MyPersistenceUnit")
@Produces
EntityManager entityMgr;

void dispose(@Disposes @MyQualifier EntityManager em) {
    em.close();
}

...

public interface Cars extends CrudRepository<Car, Integer> {
    default void someAdvancedOperation(int param1, int param2) {
        EntityManager em = CDI.current().select(EntityManager.class, MyQualifier.Literal.instance()).get();
        ... Use the entity manager for advanced JPA operations
    }
}
```

I later realized there is a problem with it in that it relies on the Jakarta Data user to supply the JPA configuration and corresponding EntityManager in the first place.  Some providers might externalize things this way, but Jakarta Data intentionally does not require it (by request of one of the providers and I also agree with them) because other JPA-based Jakarta Data providers might generate all of the JPA related stuff internally.  A spec solution to obtaining the entity manager (and other similar resources if NoSQL) needs to be something that will work for all providers.

It turns out there's a solution to obtaining underlying resources that is already in Jakarta EE and Java SE.

In Jakarta Persistence (JPA) you can invoke an unwrap method on an EntityManager to obtain the underlying resources that it uses, such as the java.sql.Connection,
```
    Connection connection = entityManager.unwrap(Connection.class);
```

Similarly, there is also an unwrap on several JDBC interfaces, such as,
```
    OracleConnection oc = connection.unwrap(OracleConnection.class);
```

We could continue this pattern to be able to obtain the underlying EntityManager for a repository with,
```
     EntityManager em = myRepository.unwrap(EntityManager.class);
```

which could be used from a default method:
```
public interface Cars extends CrudRepository<Car, Integer> {
    default void someAdvancedOperation(int param1, int param2) {
        try (EntityManager em = unwrap(EntityManager.class)) {
            ... Use the entity manager for advanced JPA operations
        }
    }
}
```

If we do this, we would need to decide whether to add the unwrap method to the base DataRepository interface, or to a separate mix-in interface (we would need a name for it).

@otaviojava 
@georgleber

**Comment by njr-11** [comment]
Having just written the above, I realized there is one big difference between JDBC/JPA unwrap and getting an entity manager from a repository, which is around whether you are getting the same vs different instance back every time, impacting whether or not a close operation should be done.  So maybe unwrap isn't the right pattern either.

**Comment by georgleber** [comment]
I felt your solution of using the CDI lookup in default functions a good approach, because it works out of the box and no change on specification is needed IMO. 

I checked the use of the use of the custom repositories in our project with Spring Data and in all places the EntityManager is injected, the query could have been done by using a `@Query` or finder method (except that a NamedQuery was used). So maybe my example on the Jakarta Data Meeting has biased us and something like EntityManager is not really needed. 

And if the user wants to use the CDI lookup in a default method, he can do so, but needs to make sure, that e.g. the EntityManager can be loaded that way. So Jakarta Data is not responsible for it. 

Nevertheless we could give an example in the documentation on how to use CDI for loading beans, that can be used in default methods.

---

BTW I have investigated in the implementation for Spring Data and how they are connecting the implementation with the custom interface. This is done by searching for the name of the interface extended by `Impl` (e.g. Interface: `CarsCustom` -> Class: `CarsCustomImpl`)

**Comment by otaviojava** [comment]
I am not a massive fan of having a method that breaks the encapsulation of the Repository, in which the main goal is to abstract the relationship with the data engine.

Eric Evan DDD:

> The Repository pattern is a mechanism for encapsulating storage, retrieval, and search behavior that emulates a collection of objects.


I need to go deep on this approach and return soon.

**Comment by njr-11** [comment]
> I am not a massive fan of having a method that breaks the encapsulation of the Repository, in which the main goal is to abstract the relationship with the data engine.

Right if we add anything here, it's probably best to keep it off of the main DataRepository interface.  It would be better to have a mix-in interface, which we would need to think more about how best to design.

**Comment by njr-11** [comment]
Clarifying a few things here:

The following doesn't directly apply to the application using Jakarta Data. It applies to Jakarta Data providers that choose to build their implementation around Java Proxy,

> ```java
> public Object invoke(Object instance, Method method, Object[] args) throws Throwable
> ```

For the application, the entry point is a default method of their repository interface. This might end up being invoked by a proxy such as above.

I'm confused by `declaringClass` here because it seems like this would point right back to the repository bean, not an EntityManager, but in general, this is a useful way to get access to CDI beans, and obtaining a repository bean certainly could be useful if your default method wants to invoke other repository methods,

> ```java
> Instance<?> instance = CDI.current().select(declaringClass);
> ```

In some cases, you might be able to get an EntityManager this way.  That depends upon whether the application had the EntityManager in the first place in order to be able to define a CDI producer for it.  If we want to solve that problem in general across all implementations that are backed by JPA, a different solution will be needed that is general enough to cover all of them.

**Comment by otaviojava** [comment]
The default method is more straightforward; we can check if it is default by the method:

```java
method.isDefault()
````

The invoker handler can do it automatically fur us:
```java
InvocationHandler.invokeDefault(instance, method, args)
```
I am talking more about a custom implementation with an interface and an implementation outside the repository.

```java
@Repository
interface UserRepository extends CrudRepository<User, String>, CustomRepository{
}

interface CustomRepository{
User cqrs(User user);
}

@ApplicationScoped
class DefaultCustomRepository {
}
```

**Comment by otaviojava** [comment]
I've created the initial step of the spec where we can give names of all of these extensions.

Please, feel free to give feedback as well:

https://github.com/jakartaee/data/pull/208
