### ISSUE TITLE
Programmatically specify sorting of results

### ISSUE THREAD

**Issue by njr-11** [jakartaee/data#21]
For a more dynamic sort option, the vendors use a parameter.

## Spring
Spring: they have a [Pageable](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Pageable.html)

```java
Pageable sortedByName =  PageRequest.of(0, 3, Sort.by("name"));
```
On the interface method:

```java
List<Product> findAllByPrice(double price, Pageable pageable);
```

## Micronaut

It has a similar approach:
[Pageable](https://micronaut-projects.github.io/micronaut-data/1.1.2/api/io/micronaut/data/model/Pageable.html)

```java
Pageable sortedByName =  PageRequest.of(0, 3, Sort.by("name"));
```

## Jakarta NoSQL

It has a [Sorts](https://www.jnosql.org/javadoc/jakarta/nosql/mapping/Sorts.html)

```java
Sorts sorts = Sorts.sorts().asc("name").desc("age");
```

```java
List<Product> findAllByPrice(double price, Sorts sorts);
```

_Originally posted by @otaviojava in https://github.com/jakartaee/data/issues/18#issuecomment-1253463626_

**Comment by otaviojava** [comment]
I believe that we can mix both.

Sorts: if the person only wants to do the orders.
Pageable: Where there is a page and a Sort.

I might want to do a dynamic order, but I don't want to paginate the result.

P.s.: I am not discussing the names and the interfaces. I'm focusing on the fact that we might support two special classes.
