### ISSUE TITLE
explain the goals of Jakarta Data and motivate/justify/explain the selected design

### ISSUE THREAD

**Issue by gavinking** [jakartaee/data#222]
Currently, section 1.1 of the specification explains its goals as follows:

> Jakarta Data works in a tight integration between Java and a persistence layer, where it has the following specification goals:
> - Be a persistence agnostic API. Therefore, through abstractions, it will connect different types of databases and storage sources.
> - Be a pluggable and extensible API. Even when the API won’t support a particular behavior of a storage engine, it might provide an extensible API to make it possible.

This is completely inadequate:

- it does not mention what _problem_ Jakarta Data trying to solve, nor motivate me to care,
- it provides me no yardstick to decide whether Jakarta Data even fulfills its own goals, 
- it doesn't explain what is meant by "agnostic" here (from the rest of the spec, it's clear that "agnostic" certainly doesn't mean "portable"), and
- it fails to consider other options already available in the Jakarta platform or the Jakarta ecosystem: why entity-specific repositories? Why not an `EntityManager`-style API? Why not Active Record like, e.g. Panache? Why not a more free-form solution like in Hibernate 6 where the _user_ gets to decide the organization of code?

Later, in the preamble for chapter 2 the notion of a "repository" is introduced and sort-of defined, with some handwaving that completely fails to capture the essential differences between an entity-specific repository, Active Record, or an `EntityManager`. Let's go through this line-by-line.

> This pattern focuses on the closest proximity of entities and hides where the data comes from.

I have no idea what this sentence means. What on earth is the _"closest proximity of entities"_? The data comes from the business. Is it the goal of Jakarta Data repositories to "hide" the business?

> The Repository pattern is a well-documented way of working with a data source. 

It's not good enough that it's documented _somewhere else_. Jakarta Data is, in its current form, a _specification for repositories_, and so it needs to document what a repository is _internally_, not by reference to a book that I have no interest in reading and would have to pay for.

Next we get a quote from Martin Fowler:

> A repository performs the tasks of an intermediary between the domain model layers and data mapping, acting in a similar way to a set of domain objects in memory. Client objects declaratively build queries and send them to the repositories for answers. Conceptually, a repository encapsulates a set of objects stored in the database and operations that can be performed on them, providing a way that is closer to the persistence layer. Repositories also support the purpose of separating, clearly and in one direction, the dependency between the work domain and the data allocation or mapping.

Unfortunately, this quote is pretty useless to us:

- Does a DAO-style repository really _"act in a similar way to a set of domain objects in memory"_? Hard to say, since I'm not even sure what that means, if it means anything at all.
- The remaining part of the quote sounds like it's describing an `EntityManager`.

The next line:

> It also becomes very famous in Domain-Driven Design: Tackling Complexity in the Heart of Software by Eric Evans.

Seems to be no more than a handwave to authority, and doesn't belong in the spec. [Yes, OK, somebody wrote a book once, _awesome_, I'm happy for them.]

The first two pages of the specification should be rewritten.

**Comment by gavinking** [comment]
Hi @otaviojava, so, what you've written here does read a _lot_ better than before. 

I'm still not satisfied, but it will do for now. We can come back later and iterate it once the rest of the specification is much better-defined.

P.S. I _really_ wish you would remove references to Domain Driven Design. There's simply _nothing_ about Jakarta Data which is specific to DDD, and it's just not relevant to the specification, in my opinion.

**Comment by otaviojava** [comment]
@gavinking 
Thank you for the guidance.
I will reopen to remove the DDD reference, then.

**Comment by gavinking** [comment]
Thank you! 🙏
