### ISSUE TITLE
consider alternatives to entity-specific repositories

### ISSUE THREAD

**Issue by gavinking** [jakartaee/data#223]
The specification does not explain why entity-specific repositories were settled on, instead of other more recent designs. The casual reader is left with the impression that the answer to this question is simply _"because that's what Spring Data does"_. I hope that's not the true answer, because, if so, it would be an inadequate answer.

The case against "repositories" (or DAOs, to those of us who remember) is that:

- they're a solution which was proposed back when each CRUD operation for every entity required significant amounts of hand-coded logic, but
- that's no longer the case, not with "modern" persistence solutions that have been entrenched in the industry for the past two decades, and
- entity-specific repositories are an unnatural way to organize the _interesting_ part of the persistence logic, that is, queries which span multiple entities.

Therefore, we do not recommend the use of the DAO pattern to our users. In Hibernate 6, we propose a _far_ more flexible solution which lets the developer declare and organize "query methods" (with generated implementations) however the developer prefers. The developer can use this facility to implement entity-specific repositories if they like, or not, if they don't like.

**Comment by gavinking** [comment]
So, for example, consider the following (speculative) solution, just for the sake of argument:


```java
@JpaRepository(unit="documents")
interface DocumentRepository {

    void insert(@Insert Document doc);
    void insert(@Insert Author book);
    void update(@Update Document doc);
    void update(@Update Author book);

    Document document(Long bookId, Type docType);
    Book author(Long authorId);

    @Query("where title like :titlePattern")
    List<Document> documentsByTitle(String titlePattern);

    @Query("where title like :titlePattern and type = :docType and author.id = authorId")
    List<Document> documentsByTitle(String titlePattern, Type docType, Long authorId);
}
```

This interface definition gives the implementation _everything it needs_ to fill in the implementations of those methods. And I didn't need to refer to any framework-defined super-interface.

Now, perhaps you dislike my `@Insert` and `@Update` annotations (and perhaps I do too, I just invented them now).

But then, if you _do_ hate them, you can write:

```java
interface EntityRepository<E> {
    void insert(@Insert E doc);
    void update(@Update E doc);
    void delete(@Delete E doc);
}
```

and you naturally recover an entity-specific repository. This `EntityRepository` could be defined by Jakarta Data, or it could just as easily be written by the user.

But this approach _does not impose entity-specific repositories on the user. It leaves that design decision up to them.

To me this is just much nicer.

**Comment by gavinking** [comment]
> this already works in Micronaut Data in a similar way. 

Awesome! It's the direction we've taken in H6.

> if you just write `void insert(Document doc)` then it is inferred from the method argument

How do you distinguish inserts from updates from deletes? By the name of the method, I suppose? 

It seems to me that an annotation is preferable. Let the user decide what they want to call the method.

> So in summary you are not required to extend from a framework specific super interface, those interfaces are merely provided as a convenience to fill in the most common operations.

Excellent, so then Jakarta Data should do the same, instead of standardizing on an older approach, which is what it is doing right now.

**Comment by njr-11** [comment]
> So in summary you are not required to extend from a framework specific super interface, those interfaces are merely provided as a convenience to fill in the most common operations.

It has been the intention of Jakarta Data for the built-in repository super interfaces to be for convenience and not required, as is being discussed here.  The following section of JavaDoc alludes to this although could be made more explicit,

```
 * <p>Built-in repository interfaces, such as {@link DataRepository}, are
 * parameterized with the entity type and id type. Other built-in repository
 * interfaces, such as {@link CrudRepository}, can be used in place of
 * {@link DataRepository}
 * and provide a base set of predefined repository methods
 * which serve as an optional starting point.
 * You can extend these built-in interfaces to add your own custom methods.
 * You can also copy individual method signatures from the
 * built-in repository methods onto your own, which is possible
 * because the built-in repository methods are consistent with the
 * same set of conventions that you use to write custom repository methods.</p>
 ```

**Comment by gavinking** [comment]
@njr-11 OK, so currently the spec says:

> The parent interface in Jakarta Data repository abstraction is DataRepository.
>
> By default, Jakarta Data has support for two interfaces. However, the core is extensible. Therefore, a provider might extend one or more interfaces to a specific data target.

That's not very clear, but it does seem to say that `DataRepository` is required.

So to do this we would need to change that and make clearer what is required for something to be a repository. I propose:

> A repository is an interface annotated `@Repository`.

And we would introduce annotations like `@Insert`, `@Update`, and `@Remove`. (Or `@Save` or whatever.) 

The annotations would be more "elemental" than interfaces like `DataRepository` or `CrudRepository` (`CrudRepository` is definable in terms of these annotations). Actually I'm inclined to think that `DataRepository` is unnecessary and could go away.

Does that sound right to you?

**Comment by graemerocher** [comment]
> @njr-11 OK, so currently the spec says:
> 
> > The parent interface in Jakarta Data repository abstraction is DataRepository.
> > By default, Jakarta Data has support for two interfaces. However, the core is extensible. Therefore, a provider might extend one or more interfaces to a specific data target.
> 
> That's not very clear, but it does seem to say that `DataRepository` is required.
> 
> So to do this we would need to change that and make clearer what is required for something to be a repository. I propose:
> 
> > A repository is an interface annotated `@Repository`.
> 
> And we would introduce annotations like `@Insert`, `@Update`, and `@Remove`. (Or `@Save` or whatever.)
> 
> The annotations would be more "elemental" than interfaces like `DataRepository` or `CrudRepository` (`CrudRepository` is definable in terms of these annotations). Actually I'm inclined to think that `DataRepository` is unnecessary and could go away.
> 
> Does that sound right to you?

Additional annotations seem useful to me to solve ambiguity or whether the user wants to have a different method name from the specified recognised patterns. I am failing to understand why just `void insert(MyEntity entity)` couldn't be recognised or would cause a problem however?

**Comment by gavinking** [comment]
>  I am failing to understand why just void insert(MyEntity entity) couldn't be recognised or would cause a problem however?

It's not a _problem_ per se. I do usually prefer explicit things over implicit things. And I feel it's more faithful to the semantics of the Java language to not build behavior/semantics into method names.

But nor is it something I'm motivated to make a big stink about. :-) What do others think?

**Comment by njr-11** [comment]
> > The parent interface in Jakarta Data repository abstraction is DataRepository.
> > By default, Jakarta Data has support for two interfaces. However, the core is extensible. Therefore, a provider might extend one or more interfaces to a specific data target.
> 
> That's not very clear, but it does seem to say that `DataRepository` is required.

Thanks for bringing this up.  As a first step, I can look into correcting the spec doc here to be consistent with the JavaDoc and making both more precise as you suggested.  This initial step ought to be non-controversial and easy to get in.

> Actually I'm inclined to think that `DataRepository` is unnecessary and could go away.

The only purpose I know of for DataRepository is for the user to communicate the entity type and id type, although in most cases I would think that can be inferred from a method's arguments or return types.  I suppose there are some rather unlikely corner cases (such as a repository with only existsBy or countBy methods) where that information could not be inferred.

> I am failing to understand why just `void insert(MyEntity entity)` couldn't be recognised or would cause a problem however?

I can see good arguments for and non wanting to the annotation (it's more concise) and for having the annotation (to be more explicit and allow flexible naming).  I'd lean toward not introducing these annotations to start out with.  We could always add them in a future version if there turns out to be a lot of interest.

**Comment by gavinking** [comment]
I'm happy to set aside the question of annotations for now, until we get much more important things sorted, and say that the names `insert`, `update`, and `delete` are magical.

**Comment by njr-11** [comment]
> So to do this we would need to change that and make clearer what is required for something to be a repository. I propose:
> 
> > A repository is an interface annotated `@Repository`.

I just spotted a nearly identical statement already in the JavaDoc, even further supporting that the spec doc just needs an update to be consistent with that.

```
 Repositories are interface classes
 * that are annotated with the {@link Repository} annotation.
 ```

**Comment by gavinking** [comment]
Here's a _very_ rough draft proposal for discussion. WDYT?


Programming model for repositories
====

A Jakarta Data repository is a Java interface annotated `@Repository`. Every non-`default` method of the interface is usually either:

- an insert, update, or delete method, 
- an annotated query method,
- an automatic query method, or
- a connection access method.

A Jakarta Data provider might extend this specification an support non-default methods which do not fall into one of the above categories. Such functionality is not defined by this specification, and programs which define such methods are not portable between providers.

An implementation of every non-`default` method is provided by the Jakarta Data implementation.

The interface may also declare `default` methods, which may call non-`default` methods.

Insert, update, and delete methods
===

An _insert method_ is a method with the signature:

    void insert(E e);

where `E` is an entity class associated with the repository.

An _update method_ is a method with the signature:

    void update(E e);

where `E` is an entity class associated with the repository.

A _delete method_ is a method with the signature:

    void delete(E e);

where `E` is an entity class associated with the repository.

Annotated query methods
===

An _annotated query method_ is a method annotated by a query annotation type. This specification defines the `@Query` annotation, which may be used to specify a query in an arbitrary query language understood by the Jakarta Data provider, but extensions to Jakarta Data might define their own query annotation types. 

For example:

    @Query(“where title like :title order by title”)
    List<Book> booksByTitle(String title, Page page);

Or:

    @Query(“delete from Book where isbn = :isbn”)
    void deleteBook(String isbn);

Each parameter of the query method must either:

- have exactly the same name and type as a parameter of the query, or
- be of type `Page` or `Sort`, TBD

The return type of the query method must match the result type of the query, etc, TBD.

Programs which make use of annotated query methods are not portable between providers.

Automatic query methods
===

An _automatic query method_ is a method with return type `E` or `List<E>` where `E` is an entity class, and where each parameter either:

- has exactly the same type and name as a persistent field or property (TBD!) of the entity class, or
- is of type `Page` or `Sort`, TBD

For example:

    Book bookByIsbn(String isbn);
    List<Book> booksByYear(Year year, Sort order, Page page)

Automatic query methods _are_ portable between providers.

Connection access method
===

A _connection access method_ is a method with no parameters which returns a type supported by the Jakarta Data provider. The purpose of this method is to provide the program with direct access to the data store. For example, if the Jakarta Data provider is based on JDBC, the return type might be `java.sql.Connection`.

**Comment by gavinking** [comment]
Note that it's straightforward to define an entity-specific repository in terms of this programming model, but the converse is not true.

In particular, this model can easily accommodate typical relational database examples like `Book`/`Author`, whereas it's unclear how to handle that example using `CrudRepository`.

**Comment by otaviojava** [comment]
I like it!
Thank you.

I would include the annotations for semantics and flexibility reasons.

Thus, Insert, Update, Delete, and Save annotations.

Thus, we can explore domain semantics as well.

```java
@Repository
interface Order {

void checkout(@Insert Order order);

@Query("any data engine query with the last five orders")
List<Order> lastestOrder(String user);
}
````

**Comment by gavinking** [comment]
@otaviojava 

> I would include the annotations for semantics and flexibility reasons.

Yes, that's my preference too, for the following reasons:

1. I simply don't like encoding APIs into "magical" method names. I don't think this is the way the Java language is supposed to be used. Sure, it might result in a trivial optimization for the developer writing a repository for the first time, but the resulting code is less self-documenting, and would appear quite mysterious to a developer who reads the code without familiarity with Jakarta Data. The fact that the method name `insert` is special is not _discoverable_.
2. I would prefer that the developer be able to freely rename those methods without changing their semantics.
3. While `insert`, `update`, `delete` seem superficially like a universal set of persistence operations, we have plenty of evidence already that they're not. Two examples: some people propose a single `save` operation; for JPA you would want `persist`, `merge`, `lock`, and and `refresh`, etc.

Therefore, I would prefer to talk generically about _lifecycle methods_ declared using _lifecycle annotations_.

Here's how I would revise the above proposal to do that:

Programming model for repositories
====

A Jakarta Data repository is a Java interface annotated `@Repository`. Every non-`default` method of the interface is usually either:

- a lifecycle method, 
- an annotated query method,
- an automatic query method, or
- a connection access method.

A Jakarta Data provider might extend this specification and support non-`default` methods which do not fall into one of the above categories. Such functionality is not defined by this specification, and programs which define such methods are not portable between providers.

An implementation of every non-`default` method is provided by the Jakarta Data implementation.

The interface may also declare `default` methods, which may call non-`default` methods.

Lifecycle methods
===

An _lifecycle method_ is a method annotated with a _lifecycle annotation_. A lifecycle method usually:

- accepts a single parameter annotated with a lifecycle annotation, whose type is a concrete entity class, and
-  is declared `void`.

This specification defines three built-in lifecycle annotations: `@Insert`, `@Update`, and `@Delete`.

For example:

    void insertBook(@Insert Book book);

Lifecycle methods with the usual signature, and declared using one of the built-in lifecycle annotations, are portable between Jakarta Data providers. _[TBD: this requirement is too strong, so we need to discuss that.]_

A Jakarta Data provider might extend this specification to define additional lifecycle annotations, or to support lifecycle methods with signatures other than the usual signature defined above. For example, a provider might support "merge" methods declared as follows:

    Book mergeBook(@Merge Book book);

Such lifecycle methods are not portable between Jakarta Data providers.

_[SNIP: rest of proposal unchanged.]_

**Comment by mp911de** [comment]
> 1. I simply don't like encoding APIs into "magical" method names. I don't think this is the way the Java language is supposed to be used.

Annotations allow for all sorts of unintended usage:

```java
void insertBook(@Insert Book book, @Delete Book otherBook);
```

The same would work for method-level annotations. A more opinionated approach by defining method signatures eliminates the need for ambiguity resolution in the first place.

> * is declared void.

Restricting to `void` immediately excludes all users who wish to use immutable class arrangements. Allowing returning the saved entity would allow for the backpropagation of generated identifiers (Mongo, Neo4j, …).

> The fact that the method name insert is special is not discoverable.

How is an annotation different from an interface defining that special `insert` method in terms of discoverability?

**Comment by gavinking** [comment]
> Annotations allow for all sorts of unintended usage:
>
>     void insertBook(@Insert Book book, @Delete Book otherBook);

Well that's true, but "magic" method names don't solve that problem. 

And incorrect usage of these annotations can be easily detected and reported at compile time by an annotation processor.

_[Please note that both projects which currently propose to implement Jakarta Data are currently based on annotation processing. We definitely don't want to _limit_ ourselves to this implementation strategy, but we should keep it in mind.]_

> A more opinionated approach by defining method signatures eliminates the need for ambiguity resolution in the first place.

As we've said above, `CrudRepository` can be easily defined in terms of this model, and we have not mentioned removing it from the specification. You can still use it for those cases where it's appropriate. Even if we _did_ remove it, which I'm not advocating, you as a user of the specification could define your own  `CrudRepository` with about 5 minutes of work.

> Restricting to `void` immediately excludes all users who wish to use immutable class arrangements. 

Yes, good point, for `record` entities we want to allow `insert` to return a new instance. I promise I will fix that! 

(Note that it will be much harder to overlook issues like this once #246 is done.)

> How is an annotation different from an interface defining that special insert method in terms of discoverability?

It's exactly the same. But that's not the motivation for using annotations instead of an interface.

The motivation for using annotations instead of an interface is that it allows a repository to manage more than one entity type, as in the [example above](https://github.com/jakartaee/data/issues/223#issuecomment-1700808815). That's a flexibility we would _especially_ like to have in the case of relational data where you have many-to-many associations. (It's not as important for document databases.)

_[Note that both projects which currently propose to implement Jakarta Data already offer the flexibility of having multiple entities belonging to a single repository. We shouldn't be limited by things that are currently implemented, but we shouldn't ignore that both projects, working completely independently, arrived at the same conclusion.]_

**Comment by gavinking** [comment]
P.S. @mp911de 

Just to clarify: I do agree with you that the `CrudRepository` interface is more typesafe than the annotations _if you're **not** using an annotation processor_ to implement Jakarta Data.

_But,_ and this is a pretty big but: under this scenario, that sort of type safety isn't available for the query methods of a repository. And they're:

- much more numerous than lifecycle method, and
- have much more complicated signatures.

So making the `insert()` method incrementally more type safe doesn't actually add much value.

On the other hand, if you _do use an annotation processor_, then _all_ of these methods, both lifecycle methods, and also the query methods, can be completely type checked at compile time.

**Comment by njr-11** [comment]
We discussed the following on the Jakarta Data call and agreed to include it as the best approach suggested thus far for obtaining the EntityManager/DataSource/Connection from the Jakarta Data provider. I created pull #248 for this.

> # Connection access method
> 
> A _connection access method_ is a method with no parameters which returns a type supported by the Jakarta Data provider. The purpose of this method is to provide the program with direct access to the data store. For example, if the Jakarta Data provider is based on JDBC, the return type might be `java.sql.Connection`.

**Comment by njr-11** [comment]
I like the idea of inferring the entity attribute from the parameter name, such as in the example above,

> ```
> @Query(“delete from Book where isbn = :isbn”)
> void deleteBook(String isbn);
> ```

Jakarta Data currently requires you to explicitly declare the named parameter with the `@Param` annotation,

```
@Query(“delete from Book where isbn = :isbn”)
void deleteBook(@Param("isbn") String isbn);
```

I think it requires an extra compile step to make the parameter names available at run time, and since we aren't making requirements on what implementations must do at compile time vs run time, I'd say we should keep the `@Param` annotation around for this purpose, while allowing the optimization to avoid specifying `@Param` when using an implementation that processes these annotations at compile time or if the user specifies the compile switch to make parameter names available at run time.  That might be some tricky wording to get into the spec, but seems worth it.

**Comment by njr-11** [comment]
Thinking about this some more, I just realized there's a problem of ambiguity between named parameters and positional parameters.  In the example above, we all know it's supposed to be a named parameter because we have mentally parsed the query text and understand that `:isbn` is a named parameter.

> ```
> @Query(“delete from Book where isbn = :isbn”)
> void deleteBook(String isbn);
> ```

However, one could also write the query with positional parameters,

```
@Query(“delete from Book where isbn = ?1”)
void deleteBook(String isbn);
```

The method signature looks the exact same in both cases.  The only difference is in the text of the query itself.  So this brings up the question: what sort of understanding (if any) is the repository provider supposed to have of the meaning of supplied queries?  Jakarta Data is currently written to assume zero knowledge, and therefore makes the distinction where usage of `@Param` indicates named parameters and absence of `@Param` indicates positional parameters.  It's a very clear distinction to the user, but also requires the user to always specify `@Param` for named parameters.

If we improve this to allow sometimes inferring named parameters from the names of parameters, what criteria would we document to the user (and repository implementations) for determining when positional parameters vs named parameters are used in the absence of the `@Param` annotation.

Maybe it could be as simple as stating that in the absence of `@Param`, any query that contains a `?` character is assumed to have positional parameters, and otherwise named parameters.  The assumption would be imperfect, but easily worked around by adding `@Param` when it doesn't default to the behavior you want.  I'm not sure what to think of this, but maybe some of the vendors who already have implementations that make the distinction can comment on how they do so.

**Comment by gavinking** [comment]
@njr-11 That's a good point. In the stuff we've implemented we do indeed tokenize the query string to recognize parameters. That's easy to do in the case of JPQL or even SQL with JDBC-style parameters. It's possible it's more difficult in some other query languages. We should check that.

**Comment by gavinking** [comment]
@njr-11 That's a good point. In the stuff we've implemented we do indeed tokenize the query string to recognize parameters. That's easy to do in the case of JPQL or even SQL with JDBC-style parameters. It's possible it's more difficult in some other query languages. We should check that.

**Comment by gavinking** [comment]
This work was completed a while ago. Jakarta Data now offers a much more freeform and flexible repository programming model, which reflects the best new thinking in this area.

See chapter 4, from the preamble on down to section 4.4. 🎉🥳
