### ISSUE TITLE
how can I define a concrete repository operation?

### ISSUE THREAD

**Issue by gavinking** [jakartaee/data#225]
I might have missed something obvious (or non-obvious), but there does not appear to be an example in the spec of how to define a _concrete_ operation of a repository. It's extremely important that this be properly documented.

Naively, it looks a bit problematic: all the examples show repositories implemented as Java interfaces, and I don't see how one would inject an `EntityManager`, a `DataSource`, a `Connection`, or whatever, into an interface. Section 3.1 talks about injecting repositories into other things, but it doesn't seem to address injection into a repository.

Nor does there appear to be any operation of `DataRepository` or `CrudRepository` which would give me access to a connection.

(I've probably just missed something here.)

**Comment by graemerocher** [comment]
since I have only been involved in this spec from an advisory perspective, I can say how this works in Micronaut Data and whether the spec wants to follow suite is up to the folks actively working on it. With Micronaut Data you can use an abstract class and inject the EntityManager (or whatever persistence technology specific interface) as constructor arguments, See:

https://micronaut-projects.github.io/micronaut-data/latest/guide/#repositories

**Comment by gavinking** [comment]
@graemerocher Right, that's the most obvious solution.

**Comment by njr-11** [comment]
This one is currently being discussed in other issues, but agreement hasn't been reached yet and so it hasn't made it into the spec.  A couple of ideas that I've thought of are:

1. Let users write default methods with an EntityManager (or DataSource or Connection) parameter where the invoking code sends in null and the repository provider substitutes in the actual entity manager for the method to use,

```
    default void myMethod(int arg1, String arg2, EntityManager em) {
        ... use entity manager
    }
```

An advantage here is that it gives the repository provider the ability to ensure the EntityManager gets closed upon completion of the method.  I'm not sure how important that is for EntityManager, but if it were a JDBC Connection, I know that's important.

2.  Add a method like `getResource(Class<T> type)` either one of the built-in repository interfaces or a mix-in interface for that purpose, that can be used to obtain the EntityManager,

```
    default void myMethod(int arg1, String arg2) {
        EntityManager em = getResource(EntityManager.class);
        ... use entity manager
    }
```

The repository provider could close resources here after the method completes, although it might be a little less straightforward to do it.

There are probably a variety of other options as well. It would be good to standardize one.

We don't have abstract classes as repositories defined in Jakarta Data yet, but that could get added.

**Comment by gavinking** [comment]
The way this works in Hibernate 6 is as follows. I write:

```java
interface Queries {
    EntityManager entityManager();

    // generated
    @Find
    List<Book> findBooksByTitle(String title);

    // handwritten
    default List<Book> findBooksByTitleAndType(String title, String type) {
        entityManager()
                .createQuery("from Book where title like :title and type = :type", Book.class)
                        .setParameter("title", title)
                        .setParameter("type", type)
                        .setFlushMode(COMMIT)
                        .setMaxResults(100)
                        .getResultList();
    }
}
```

The annotation processor sees that we have an operation with no parameters which returns something "session-like" (`EntityManager`, or something similar) and fills it in.
