### ISSUE TITLE
Define the minimal set of portable functionality

### ISSUE THREAD

**Issue by gavinking** [jakartaee/data#227]
Jakarta Data currently fails to specify a core minimum set of functionality which all implementations must support and which must work portably across implementations. 

- Much of the specified functionality appears to be optional, in that support for it depends on the capabilities of the data store.
- Most of the features have undefined or under-specified semantics.
- The specification almost never seems clearly to impose any hard requirement on implementations.

In its present state, I have no expectation of portable behavior _even for implementations which target the same data source_.

**Comment by njr-11** [comment]
This area of the spec definitely needs work.  If everyone can help collect specific examples within this issue, it will improve the changes we identify all of the places and get them addressed.  I agree example code in specs does not convey requirements. The purpose of examples is to provide a helpful illustration to the reader to more quickly understand requirements and usage that are directly spelled out by the spec.  Let's improve this in all the places it is needed.
