### ISSUE TITLE
Proofread and copyedit the spec

### ISSUE THREAD

**Issue by gavinking** [jakartaee/data#228]
A native English speaker with specification-writing experience needs to spend some time rewording the specification.

**Comment by gavinking** [comment]
I'm informed by @maxandersen that this issue report could be taken the wrong way. To clarify: as a native speaker with lots of experience at writing specs, I am of course volunteering to do this work.

**Comment by otaviojava** [comment]
Hey, I got your point, and you are right; there are a lot of issues for improvement. I have almost zero experience writing a spec from scratch and am not a native speaker.


Thank you. I will need as much help as needed, mainly because I do it in my free time as a community person.

**Comment by njr-11** [comment]
Additional work that is needed under this issue:
- [ ] The **Copyright** section has a number of variables that are not being substituted when I build locally, as well as in the officially-built M1 spec doc, https://jakarta.ee/specifications/data/1.0/data-1.0.0-m1.
- [ ] Section **1.3. Conventions** is empty. We should consider removing it unless there are plans to author something for that section.
- [ ] Section **1.4. Jakarta Data Project Team** should be updated to include the names of people who have made significant contributions to the spec. We should consider voting in some of these people as committers and add them under that section as well.
