### ISSUE TITLE
Limit results of normal queries (without pagination)

### ISSUE THREAD

**Issue by njr-11** [jakartaee/data#23]
**Description**

As a:

- [ ] Application user/user of the configuration itself
- [x] API user (application developer)
- [ ] SPI user (container or runtime developer)
- [ ] Specification implementer

...I need to be able to:
restrict the number of results that are returned by queries (including when I'm not using pagination)

...which enables me to:
load only what I need to avoid wasting resources and perform better.

Some of the existing solutions, including [Spring Data](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.limit-query-result), [Micronaut Data](https://micronaut-projects.github.io/micronaut-data/latest/guide/), [Apache DeltaSpike](https://deltaspike.apache.org/documentation/data.html), all support `findFirst(#)By...` syntax that enables method name pattern-based queries to limit results. In all of these the number is optional and defaults to 1 (the first) when not included.

We could do the same in Jakarta Data and it would cover the method name pattern-based queries,

```
List<Employee> findFirst10ByLocationOrderBySalaryDesc(String location);
```

To cover queries provided with `@Query`, we could have,

```
@Query(...)
@Limit(10)
List<Employee> highestSalariedIn(String location);
```

**Comment by otaviojava** [comment]
We have the https://github.com/jakartaee/data/issues/21, where it defines sorting, limit, and skip.
I like the approach of a method by the query; however, I'm afraid of more annotations, especially when the other implementations do not have them.

:+1: ```findFirst(#)By```

:-1: ```Limit```

**Comment by njr-11** [comment]
I think you're right that programmatically specifying the limit would be better than annotatively in this case because there isn't any benefit to knowing the limit upfront, so it's a different situation than order by.

If we use what is in #27 then a user would specify programmatically as:

```
@Query(...)
List<Employee> highestSalariedIn(String location, Pageable pagination);
...
found = employees.highestSalariedIn(location, Pageable.of(1, 10));
```

which is great if the user wanted pagination, but awkward the user didn't.
It seems like we would need a `Limit.of(10)` to properly allow for that,

```
@Query(...)
List<Employee> highestSalariedIn(String location, Limit limit);
...
found = employees.highestSalariedIn(location, Limit.of(10));
```

**Comment by otaviojava** [comment]
Nice, The will the ```Limit``` have both? 
I mean, skip and start?

**Comment by njr-11** [comment]
> Nice, The will the `Limit` have both? I mean, skip and start?

Yes, good idea to optionally include a starting position as well, which will make it more flexible.

```
public static Limit of(long maxResults); // startAt defaults to first result
public static Limit of(long maxResults, long startAt);
```
