### ISSUE TITLE
migrate away from the use of stringly-typed field references

### ISSUE THREAD

**Issue by gavinking** [jakartaee/data#230]
The specification has examples like `Sort.desc("yearBorn")`, `@OrderBy("age")`, etc.

In Hibernate and JPA we now strongly discourage this sort of untypesafe code. Instead, we leverage the JPA static metamodel generator to express _typesafe_ references to entity attributes, for example, `Order.asc(Book_.title)`.

You can see examples [here](https://docs.jboss.org/hibernate/orm/6.3/introduction/html_single/Hibernate_Introduction.html#paging-and-ordering).

Jakarta Data should carefully consider how it can integrate with the JPA static metamodel, or extend the idea to non-JPA entities.

**Comment by njr-11** [comment]
The typesafe aspect of this is nice. I found an example [here](https://docs.jboss.org/hibernate/orm/5.4/topical/html_single/metamodelgen/MetamodelGenerator.html) of defining a metamodel class in Hibernate,

```
@StaticMetamodel(Order.class)
public class Order_ {
    public static volatile SingularAttribute<Order, Integer> id;
    public static volatile SingularAttribute<Order, Customer> customer;
    public static volatile SetAttribute<Order, Item> items;
    public static volatile SingularAttribute<Order, BigDecimal> totalCost;
}
```

We could potentially define something similar where the fields are all of type String to make it generic for all provider types to avoid a dependency on JPA classes.

One potential drawback could be the inability to declare the constant-like fields final, allowing the possibility that some errant code might alter its value, although that seems very unlikely to happen.

**Comment by dstepanov** [comment]
Micronaut Data would be able to detect incorrect `@OrderBy("age")` at the compilation time. The other case would be a runtime error.

**Comment by Sanne** [comment]
> Micronaut Data would be able to detect incorrect `@OrderBy("age")` at the compilation time. The other case would be a runtime error.

Right, Quarkus could also do that, but it's much nicer to the developer to get guidance/autocompletion while typing, which is what the Hibernate metamodel approach would provide.

Also, Java is a type-safe language so as a matter of principle I believe the metamodel approach is a better fit.

**Comment by graemerocher** [comment]
annotation processors can provide autocompletion for IDEs too. Just saying 🙂

**Comment by graemerocher** [comment]
FWIW Micronaut supports incremental annotation processing and code coverage only breaks if you use a processor (Lombok) that breaks the AST

**Comment by gavinking** [comment]
@otaviojava @njr-11 One thing I didn't check, but that we probably need to make sure of, is that the static metamodel defined by Jakarta Data is compatible with the one defined by Jakarta Persistence, in the sense of it being a subset.

I _believe_ that's true, but I still need to make sure.

**Comment by otaviojava** [comment]
Thank you @gavinking IMHO: It should be compatible; otherwise, it is a non-goal.

**Comment by gavinking** [comment]
Folks, what happened with this? 

I thought we had already made good progress on this, and then I went looking to review what was there right now, and I didn't find anything. 

It would really suck if we went out with `Sort` still being stringly-typed, IMO.

**Comment by otaviojava** [comment]
We discussed this topic last month, and as much as we wanted, we needed to define priorities, and the core has the highest priority.

We had a lot of loose ends within the specification, and we focused on the core as the highest priority.
We needed the definition of entity, repository, life-cycle, etc.

That will be the next step as soon as we close this core.

**Comment by njr-11** [comment]
In case the decision is made to bring back static metamodel in version 1.0, I put together the latest we had for it into a pull #394 .  I tried it out and it still works and is compatible with what is in the spec.  I listed what I remember the concerns being on that pull.

**Comment by gavinking** [comment]
Thanks! 🙏

**Comment by otaviojava** [comment]
> @otaviojava I thought the agreement we had on deferring this to next release was that you were first going to get Gavin's okay on doing that before deferring it since he opened the issue. Did that part get missed?

He agreed, @gavinking check the email:
Subject: "Please review Jakarta Data spec!"
Date: Wed, Nov 1, 1:10 PM

**Comment by gavinking** [comment]
Just a bit of miscommunication. My "Yes, definitely!" was in response to "Can you review it?". 

No worries at all, let's talk this over on a call, when we all have time.

**Comment by otaviojava** [comment]
> Just a bit of miscommunication. My "Yes, definitely!" was in response to "Can you review it?".
> 
> No worries at all, let's talk this over on a call, when we all have time.

For sure, we can.
Indeed, that was what we agreed: finish everything and return to this topic, mainly because this is a topic one. 
It it left some points at the spec to fix.
