### ISSUE TITLE
On integration with Bean Validation and Jakarta Persistence

### ISSUE THREAD

**Issue by emmanuelbernard** [jakartaee/data#237]
Looks like applying validation on save and saveAll is defined. But ti is also defined in JPA, JPA will validate entities upon insertion or update. Describe the mechanism to avoid double callor explicit in the spec that the double call is an expected behavior (maybe to do validation in sync vs async?)

**Comment by keilw** [comment]
While the Persistence Spec discusses "3.6. Bean Validation" there is no dependency in JPA to Validation.

**Comment by otaviojava** [comment]
We do the same; it will work as the capability or extension of the specification if the vendor wants it to do so.

**Comment by njr-11** [comment]
Pull #231 , which is currently in progress, covers Jakarta Validation, and does so in a way that does not introduce compile dependencies on Jakarta Validation.  I'm intending to get some updates for CrudRepository in there as well, once another pull merges.  If either of you have comments, please add them to #231 .

**Comment by otaviojava** [comment]
We were closing this issue once we had a PR fixing this point.
Thank you for the feedback, and feel free to reopen this PR as many times that make sense or create a new one.
