### ISSUE TITLE
Keep the "core" API DB-system agnostic

### ISSUE THREAD

**Issue by keilw** [jakartaee/data#238]
Free choice of Database types

As a:

- [ ] Application user/user of the configuration itself
- [ ] API user (application developer)
- [ ] SPI user (container or runtime developer)
- [ ] Specification implementer

...I need to be able to: 

use Jakarta Data with the database system/type of my choice.

...which enables me to:

keep the dependencies and size or my application small enough, especially in a Cloud-Native Microservice environment like the Core Profile.

**Comment by otaviojava** [comment]
Thank you for reminding; that is our core point.
