### ISSUE TITLE
basic programming model for entities

### ISSUE THREAD

**Issue by gavinking** [jakartaee/data#246]
In #223 we're discussing the base-level programming model for repositories. But if we hope to have any sort of portability, we need to define at least _some_ sort of minimal programming model for Java classes which represent entity data. Of course, that's not enough to make code _truly_ portable, since  there is also a need for metadata mapping entities to the data store, but it does provide a foundation that other specs like NoSQL can build on.

So it seems to me we need to contemplate _at least_ the following:

- fields/properties of "simple" or "basic" type, and
- "embeddable" objects.

So I suppose we could say that, at minimum, a provider must support persistent fields of type:

- all Java primitive types, and their `java.lang` wrapper types
- `String`
- `LocalDate`, `LocalDateTime`, `LocalTime`, `Instant`
- `UUID`
- `BigInteger`, `BigDecimal`
- `byte[]` ?
- `enum` types ??

In particular, an entity must have a unique identifier composed of these types. (I'm not sure if we need to say something about _generated_ identifiers at this level of abstraction.)

Next, I believe it's important that we require support for defining an entity by composition. So we would also require support for a field whose type is a concrete class with fields which are also legal types (recursively). These "embeddable" classes are not entities and do not have their own persistent identity.

Support for this sort of composition seems like a pretty basic requirement for mapping document databases (please correct me if I have this wrong). And it's also pretty natural in relational databases, where the embedded object maps to a UDT, or simply gets flattened into columns.

Now, I guess that the document database case also pushes us toward also allowing some sort of support for _collections_ of basic types or embeddables. I'm not clear on the details of what must be supported here. I do know that this is a much less natural thing in relational databases, but it's possible (Jakarta Persistence requires it, for example), and such a collection can be mapped to a SQL array type, to a nested table, or to an auxiliary table.

Finally, what do we say about associations _between_ entities? I know they're super-important in the relational model, but perhaps we simply leave them undefined at the level of abstraction of the Jakarta Data spec. (I have to go and read what the NoSQL spec says.)

Anyway, I can formalize the above once I have a better understanding of the non-relational case. Note that I would not actually mention any sort of annotations for defining entities and their mappings, since those would be data store-specific, and defined externally to Jakarta Data.

Finally, we need to get into the whole issue of how entity classes are instantiated. Jakarta Persistence requires a default constructor and uses direct field access to set state. But here we could also allow immutable entity classes, and those are best represented as Java `record`s.

**Comment by otaviojava** [comment]
Unfortunately, the NoSQL spec is far behind the Jakarta Data; I learned how to write a proper spec now through those issues, and I will replicate what I know to the NoSQL spec; however, it will require time.

**Comment by njr-11** [comment]
Thanks for writing this up.  It's an excellent list of details we need to get into the specification.  The minimum set of persistent fields is definitely something we overlooked.  One part I don't think we ought to include is how entity classes are instantiated, because that is a detail of the entity model that is defined by another specification (such as Jakarta Persistence or Jakarta NoSQL or a vendor specific entity model).  The Jakarta Data specification would state that it must be possible to use the Jakarta Persistence Entity for relational database (or something to that effect) and state any limitations that we want to place on that entity model when used with Jakarta Data, but we can defer to the Jakarta Persistence specification on details such as how it allows entities to be instantiated.

**Comment by michael-simons** [comment]
Neo4j employee here.

Types and all of this are the least issue from our perspective, we do support all of them in the official driver.
We also do support collections, but not as properties on nodes and relationships, but as aggregates returned in queries.

**Comment by otaviojava** [comment]
We created the first step on this PR:

https://github.com/jakartaee/data/pull/254
