### ISSUE TITLE
Ensure API classes are in a package that makes sense for them

### ISSUE THREAD

**Issue by njr-11** [jakartaee/data#259]
Otavio raised this [comment](https://github.com/jakartaee/data/pull/258#discussion_r1324141108) during a code review

> IMHO: it should be compatible not just with the repository domain but with all Data patterns that we might bring in the future; thus, it should be in the data package.

Although the comment was directed at a specific class being introduced, it's good general point to consider for other API classes that we have already defined.  We have a number of classes in the `repository` package that shouldn't be limited to usage by repository pattern only. For example, the `Sort` class has general usefulness that could apply to other patterns that might be introduced in the future.

Here is a _one idea_ for arranging packages:

- jakarta.data
Streamable, Sort, Direction, Limit get moved here

- jakarta.data.exceptions
No changes

- jakarta.data.model
(TBD - if we add API classes for static metamodel)

- jakarta.data.page
Pageable, Page, Slice, KeysetAwarePage, KeysetAwareSlice, KeysetCursor, Pagination get moved here

- jakarta.data.repository
Other classes remain here

Any thoughts on this before we put a pull together for it?

**Comment by otaviojava** [comment]
Just one: You read my mind.
