### ISSUE TITLE
Repository to (optionally) return managed JPA entities (JPA integration)

### ISSUE THREAD

**Issue by lprimak** [jakartaee/data#264]
**Description**

As far as I understand it, the repository finder methods return POJOs and not managed entities. In order to integrate with existing JPA codebases, it would be very useful if managed entities were returned.

As a:

- [ ] Application user/user of the configuration itself
- [x] API user (application developer)
- [ ] SPI user (container or runtime developer)
- [ ] Specification implementer

All that would be needed is a reference to EntityManager. I propose to infer EntityManager from CDI,
similar to what's implemented here: https://docs.flowlogix.com/#section-daohelper
```
@Inject
// Inject default EntityManager
@EntityManagerSelector
MyRepository<Entity, Key> repository;
```
```
@Inject
@EntityManagerSelector(NonDefaultEM.class)
MyRepository<Entity, Key> repository;
```
where `NonDefaultEM` is a custom `@Qualifier` annotation that points to a producer method that injects the appropriate EM.
Default would be no-qualifier injection, which would work in most cases.

**Comment by otaviojava** [comment]
Hello @lprimak, how are you?

I updated the spec to return the EntityManager using convention methods.

Does it help?

https://github.com/jakartaee/data/blob/main/spec/src/main/asciidoc/repository.asciidoc#resource-accessor-methods

**Comment by lprimak** [comment]
Hi, Otavio!
First of all, thanks for your great work on this spec. It looks very promising!

* Is my assumption that the finder methods don't return managed entities correct?

If my assumption is correct, I would want the ability to pick which `EntityManager` manages the returned entities. Since an application may have multiple databases and entity managers, it's not enough for the implementation to pick one. I want to be able to pick one in application code, thus `@EntityManagerSelector` annotation.

This would also permit the return of managed entities from finder methods, using the *correct* entity manager.

Hopefully this makes things more clear.

Thank you!

**Comment by lprimak** [comment]
>  I think we should defer discussion over managed entities to the subsequent version of Jakarta Data.

Understood.

I think in that case, spec needs to be updated to say so explicitly, with a caveat that the feature may be added in the future to integrate more tightly with JPA

Does spec mention how a persistence unit is picked currently, it there are multiple ones? I might have missed it or it's not there.
Does it use persistence.xml file or not?

**Comment by njr-11** [comment]
> Does spec mention how a persistence unit is picked currently, it there are multiple ones? I might have missed it or it's not there.
> Does it use persistence.xml file or not?

The spec has `dataStore` on the `@Repository` annotation for selecting which to use.  This is provided as a String for general compatibility with a variety of providers, some JPA-based, some JDBC-based, some NoSQL-based, or other.  The intention is to eventually be able to use it with Jakarta Config for more detailed configuration.  But Jakarta Config won't be in Jakarta EE 11.  In the mean time, you just point it at the name of a resource that your provider requires.  That could be a persistence unit name for JPA, a DataSourceDefintion name or JNDI name, or some other identifier.  Jakarta Data specification itself does not mandate the use of any XML files, including those from JPA.  That part is up to the provider, whose responsibility it is for documenting any underlying resources that it requires and their configuration.

**Comment by lprimak** [comment]
Ah, that's what I was missing, thanks Nathan!

**Comment by lprimak** [comment]
Looks like this is already covered by #224

**Comment by gavinking** [comment]
> The spec has `dataStore` on the `@Repository` annotation for selecting which to use. This is provided as a `String` for general compatibility with a variety of providers, some JPA-based, some JDBC-based, some NoSQL-based, or other. 

Sorry, @njr-11, I had missed this comment.

That indeed is reasonable as a way to disambiguate datastores and persistence units by name.

On the other hand, it does let me use CDI qualifiers, as in my previous [comment](https://github.com/jakartaee/data/issues/264#issuecomment-1959470403).

**Comment by gavinking** [comment]
Alternatively, I guess you could used CDI method injection, for example:


```java
@Repository
interface JpaRepo {

    void init(@DocumentDatabase EntityManager entityManager);

     ...

}
```

But I actually hate method injection and I guess I think this is significantly worse. (If, admittedly, more standard.)

**Comment by lprimak** [comment]
I personally like the CDI qualifier solution, but either one will work for me :)
Thank you guys!

**Comment by gavinking** [comment]
I have opened issues #476 and #470, and I would like to close this issue. Any objections?

**Comment by njr-11** [comment]
> I have opened issues #476 and #470, and I would like to close this issue. Any objections?

That sounds good. I'll spend some time looking into/thinking about whether it could make sense to have both ways of configuring which data source/persistence unit reference to use

**Comment by gavinking** [comment]
>  I'll spend some time looking into/thinking about whether it could make sense to have both ways of configuring which data source/persistence unit reference to use

Perfect!
