### ISSUE TITLE
Milestone 1.0 Release

### ISSUE THREAD

**Issue by KyleAure** [jakartaee/data#267]
## Proposal

Now that we have gone through a few beta releases and the Jakarta Data specification has matured we should consider a 1.0.0-M1 milestone release. This will help to solidify what we plan to release for Jakarta EE 11, and to further encourage the involvement of implementations to provide feedback.

This will also be a good opportunity to verify our Jenkins release builds to ensure everything is configured correctly to build and publish artifacts.

## Outstanding work

> Issues/Pulls we want to finish before a Milestone 1.0 Release
> Discussed on the last Jakarta Data call see [Meeting Minutes](https://docs.google.com/document/d/1MQbwPpbEBHiAHes1NaYTJQzEBGUYXxaJYw5K-yj053U/edit))

- [ ] https://github.com/jakartaee/data/pull/266 (Re-add insert/update)

House keeping prior to milestone release

- [ ] https://github.com/jakartaee/data/pull/276

Let me know if I missed anything.

**Comment by KyleAure** [comment]
Milestone 1 release has been staged:

- Branch: [RELEASE-1.0.0-M1](https://github.com/jakartaee/data/tree/RELEASE-1.0.0-M1)
- Tag: [1.0.0-M1](https://github.com/jakartaee/data/tree/1.0.0-M1)
- Staging Repo: https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/data/

FYI @njr-11 @otaviojava - please verify that the M1 staged release looks good and then we can go forward with getting this release to maven central.

**Comment by njr-11** [comment]
> Milestone 1 release has been staged:
> 
>     * Branch: [RELEASE-1.0.0-M1](https://github.com/jakartaee/data/tree/RELEASE-1.0.0-M1)
> 
>     * Tag: [1.0.0-M1](https://github.com/jakartaee/data/tree/1.0.0-M1)
> 
>     * Staging Repo: https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/data/
> 
> 
> FYI @njr-11 @otaviojava - please verify that the M1 staged release looks good and then we can go forward with getting this release to maven central.

This looks great Kyle!  It will be nice to have all the M1 JavaDoc with the lifecycle annotations in it out there so that developers who experiment with M1 will be able to reference it when trying out Jakarta Data!  Thanks for getting this put together so quickly as well, allowing some time for providers to get M1 betas out there in advance of JakartaOne.

**Comment by otaviojava** [comment]
🚀 Go M1!

**Comment by KyleAure** [comment]
Milestone 1 release has been released:

- Release Repo: https://jakarta.oss.sonatype.org/content/repositories/releases/jakarta/data/
- Maven Repo: https://repo1.maven.org/maven2/jakarta/data/

Time for a coffee: ☕
