### ISSUE TITLE
Question about the `Attribute` class in the `StaticMetamodel`

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#296]
**Goal:**
I am seeking clarification on the usage and necessity of the `Attribute` class in the `StaticMetamodel` and whether it is essential for the Jakarta Data specification.

**Context:**
I have been working on creating a Java Annotations Processor for the `StaticMetamodel`, specifically focusing on the `Attribute` class. However, after carefully examining the class and its usage within the specification, I am questioning its relevance and potential drawbacks.

**Concerns:**

1. **Safety:** The `Attribute` class appears to have a potential safety issue. The `init` method allows direct modification of attributes. For instance, one can do something like:
   
   ```java
   Product_.price.init(null);
   ```
   
   This seems to bypass encapsulation and allows users to modify attributes inadvertently or intentionally, which raises concerns about data integrity.

2. **Delay Layer:** The `Attribute` class seems to act as a delay layer, wrapping the `AttributeInfo` without introducing new information. This abstraction layer could increase memory usage without significant benefit, affecting efficiency.

3. **Extensibility:** The current approach using the `Attribute` class may not allow easy extensibility. If there is a need to introduce new capabilities, such as NoSQL-specific functionalities (e.g., greater than or equal conditions), the current approach might not be conducive to such extensions.

**Questions:**

Considering these concerns, I would like to ask if there is a valid and essential reason for the existence of the `Attribute` class within the Jakarta Data specification. Can we consider removing this class and allowing Java annotation processors to handle these operations directly?

**Suggested Alternative:**

An alternative approach could be to provide interfaces or abstract classes for specific attribute types, allowing for extensibility. For example:

```java
public interface NumberAttributeInfo extends AttributeInfo {
    Criteria eq(Number number);
    Criteria gt(Number number);
    Criteria gte(Number number);
}

public class Person_ {
    public static final AttributeInfo name = new Person_IDField(); // or any generated terminology
    public static final NumberAttributeInfo age = new Person_AgeField();
}
```

This approach might offer more flexibility without needing the `Attribute` class.

**Additional Notes:**

I'm not sure if the limitations I mentioned are due to the use of reflection, but the Jakarta Data specification should not unduly limit the capabilities of Java Annotation Processors.

**Comment by njr-11** [comment]
> 1. **Safety:** The `Attribute` class appears to have a potential safety issue. The `init` method allows direct modification of attributes

This is solved by enforcing one-time initialization and arranging for the Jakarta Data provider to perform its initialization before the instance is injected into to the application.  An application is trying to behave badly by invoking `init` will find its attempts to do so ineffective because all subsequent initialization attempts are ignored.


> 2. **Delay Layer:** The `Attribute` class seems to act as a delay layer, wrapping the `AttributeInfo` without introducing new information. This abstraction layer could increase memory usage without significant benefit, affecting efficiency.

The capability is entirely opt-in on the part of the application, on a case-by-case basis.  No StaticMetamodels are created by default. An application that wants the StaticMetamodel asks for one for a specific entity.  As far as not introducing new information, that's the whole point of this: to give you the same information in a type-safe manner.


> 3. **Extensibility:** The current approach using the `Attribute` class may not allow easy extensibility. If there is a need to introduce new capabilities, such as NoSQL-specific functionalities (e.g., greater than or equal conditions), the current approach might not be conducive to such extensions.

This one has me confused because it was written this way specifically to allow the extensibility that you claim will not be allowed.  A future version of the spec will have the option of being able to add usage like,

```
Person_.age.gt(20);
Person_.name.startsWith("O");
```

> I'm not sure if the limitations I mentioned are due to the use of reflection, but the Jakarta Data specification should not unduly limit the capabilities of Java Annotation Processors.

We prototyped this before introducing it to ensure it was workable, and used reflection for that.  It is unclear to me what the problems are related to this because we did not run into any.

**Comment by njr-11** [comment]
> But Imagine that I want to implement features outside the spec, as I said previously. I can create an interface that extends `AttributeInfo`? Nope,

What you were saying before was not very clear.  You only said extensibility, and I answered in terms of version next of Jakarta Data being able to extend the pattern.  Now you are talking about a different type of extensibility, where vendors build their own vendor-specific API on top of it.  Specifications should not go out of their way to help facilitate vendor specific API.  If a vendor wants additional API, it can just define its own.  I don't see any reason why a vendor should need to define its own API as some sort of mix-in with spec-defined API.

**Comment by njr-11** [comment]
Also, you alternative doesn't make any sense to me because it refers to artifacts like `Person_IDField()` and  `Person_AgeField()` without defining what they are and where they came from.  It is not complete enough for me to be able to provide any evaluation of it.

**Comment by njr-11** [comment]
> In the end, the user interacts with the `AttributeInfo` methods.
> Why should we have this one?

No, the user interacts with the `Attribute` class and the results of the methods that the user invokes upon it.  The sole purpose of `AttributeInfo` is for the Jakarta Data provider to supply implementation for an `Attribute`, thus allowing the `Attribute` to be declared `static final` and behave as a constant to the application.  The approach might be awkward to the Jakarta Data provider, but it is very simple for the user, and that is the point.

**Comment by otaviojava** [comment]
> Also, your alternative doesn't make any sense to me because it refers to artifacts like `Person_IDField()` and `Person_AgeField()` without defining what they are and where they came from. It is not complete enough for me to be able to provide any evaluation of it.

Those classes are samples if I want to use Java Annotation Processor, which I can generate those classes at the build time.

You can check this one as a sample: https://github.com/soujava/annotation-processors/tree/master
I can generate as [many classes as I want](https://github.com/soujava/annotation-processors/blob/master/processor/src/main/java/org/soujava/metadata/processor/ClassAnalyzer.java#L78-L84), and IMHO: once Java Annotation Processor belongs to the Java SE spec, the Jakarta Data Spec should not get against it.

I used the Jakarta Persistence as a sample; they are not defining it either and let the vendors define it to use reflection or Java Annotation Processor.


As I said, the terminology does not matter; it can come from both runtime and build time.

**Comment by otaviojava** [comment]
> > In the end, the user interacts with the `AttributeInfo` methods.
> > Why should we have this one?
> 
> No, the user interacts with the `Attribute` class and the results of the methods that the user invokes upon it. The sole purpose of `AttributeInfo` is for the Jakarta Data provider to supply implementation for an `Attribute`, thus allowing the `Attribute` to be declared `static final` and behave as a constant to the application. The approach might be awkward to the Jakarta Data provider, but it is very simple for the user, and that is the point.

IMHO: from the use perspective, it should not matter once it gets:

```java
Person_.age.name();
Person_.age.asc();
```
And the user can do it without this class inside the spec.

As I said, it is fine to be the Open Liberty way, but make it the right way, it does not make sense.

**Comment by njr-11** [comment]
> I like the CDI approach, that allows extensions such as a portability functionality. IMHO: This is a good software design approach.
> 
> Why not do the same here?

I'm getting very confused here.  I think we both need to be more explicit.   When I prototyped what is currently defined in the spec for StaticMetamodel, I used CDI as follows, although certainly the CDI Lite extension could be used instead,

```
    public <T> void annotatedStaticMetamodel(@Observes @WithAnnotations(StaticMetamodel.class) ProcessAnnotatedType<T> event) {
        AnnotatedType<T> type = event.getAnnotatedType();
        StaticMetamodel staticMetamodel = type.getAnnotation(StaticMetamodel.class);
        Class<?> entityClass = staticMetamodel.value();
        ...
```

Then I used `type.getJavaClass()` to get the class that is annotated with StaticMetamodel and used reflection to look for the fields that need to be initialized and supplied an implementation of AttributeInfo to each.  You can probably find much more efficient ways to achieve the same, but I'm struggling to understand where what is currently in the spec is an impediment to anything other than vendors who think they want to mix in an API of their own that inherits from Attribute, which I've said before is a scenario we don't need to care about, which you put a thumbs up on.

**Comment by otaviojava** [comment]
Okay, I will draw for both, with reflection and without reflection, In a scenario where the 

Given I have this entity:

```java
@Entity 
public class Person{
@Id 
private Long id;
@Column 
private String name:
}
```

# Without Reflection

[Hibernate](https://docs.jboss.org/hibernate/orm/6.3/introduction/html_single/Hibernate_Introduction.html#generator). I would go to Java Annotation Processor.

That is why I like the JPA approach to only have hibernate.

Thus, I will observe the `Entity` annotation and generate the following classes:

* Person_
* Person_IdField for representing the Id field(Please ignore the name; you can use anyone)
* Person_NameField for representing the name field.

Where the `Person_`will have the structure below:


```java
@StaticMetamodel(Person.class)
public class Person_ {

private static final AttributeInfo id = new Person_IdField();

private static final AttributeInfo name = new Person_NameField();

}
```

The fill will be generated as well. For example: Person_IdField.

```java
public class Person_IdField implements AttributeInfo {

@Overwrite
public Sort asc(){
  return Sort.asc("id");
 }

\\more implementation here
}
```



All of those structures will be defined at build time. 
Quarkus might do a similar way, however, using bytecode modification.

This approach can work with both CDI and CDI Lite.


# Reflection

I would go pretty much the way that you did, so:

* I would create an `Attribute` class.
* I can `Entity` annotation and generate those classes, which field will have this `Attribute' as field.


```java
    public <T> void annotatedStaticMetamodel(@Observes @WithAnnotations(Entity.class) ProcessAnnotatedType<T> event) {
      //generate the classes here.
```


# Opion

I recommend using Java Annotation processor, mainly because once the user changes a field, you can update the structure without any application impact on runtime.

So, I update with a new field:

```java
@Entity 
public class Person{
@Id 
private Long id;
@Column 
private String name:
@Column 
private int age:
}
```

This will generate the new classes: 
* Person_
* Person_IdField 
* Person_NameField
* Person_AgeField 


Please check the Jakarta Persistence spec; we can work with both options:

https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0.html#metamodel-api-interfaces

**Comment by otaviojava** [comment]
Note, the Jakarta Persistence only works with Java Annotation processor:

> In the typical case, an annotation processor is expected to be used to produce static metamodel classes corresponding to the entities, mapped superclasses, and embeddable classes in the persistence unit. A static metamodel class models the persistent state and relationships of the corresponding managed class. For portability, an annotation processor should generate a canonical metamodel as defined below.

https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0.html#static-metamodel-classes

And that makes more sense, mainly, because it should be available as static code, once it is a `StaticMetamodel` annotation.

**Comment by njr-11** [comment]
Unless the user has to go through special steps to pre-generate classes (which I am against requiring in Jakarta Data), code like the following will not compile:

```
@StaticMetamodel(Person.class)
public class Person_ {

private static final AttributeInfo id = new Person_IdField();

private static final AttributeInfo name = new Person_NameField();

}
```

(Also note that `private` makes the fields useless - I assume that was a mistake).

If the user does not supply a value, then the field cannot be `static final`, and would need to be something like what JPA does:

```
@StaticMetamodel(Order.class)
public class Order {
    public static volatile ...
```

However, if we switch to a pattern that relies on `static volatile` as JPA does, it would directly violate your goal/concern number 1 that you raised against the current design.  I demonstrated that the current design is not actually vulnerable to that issue because of steps that we have architected into the current design to only honor the very first `init` and ensure that the Jakarta Data provider gets to invoke it prior to injecting.  However, the `static volatile` design of JPA is completely vulnerable to the issue that you raised:

> 1. **Safety:** The `Attribute` class appears to have a potential safety issue. The `init` method allows direct modification of attributes. For instance, one can do something like:
>        ```java
>        Product_.price.init(null);
>        ```
>        This seems to bypass encapsulation and allows users to modify attributes inadvertently or intentionally, which raises concerns about data integrity.

That said, I would consider switching to the sort of design that is used as JPA if that is what you are asking for.  But you need to understand that doing so achieves the opposite of your stated goal/concern number 1 at the top of this issue.  Please confirm if that is really what you want.

**Comment by otaviojava** [comment]
@njr-11 You are assuming that the user should generate this code; nope, as we have in Jakarta Persistence, the provider, not the developer, should create this code.

In my sample, the unique participation of the user is creating the entity:

```java
@Entity 
public class Person{
@Id 
private Long id;
@Column 
private String name:
@Column 
private int age:
}
````

Everything else should go to the Jakarta Data provider using reflection or Java Annotation Processor.

**Comment by otaviojava** [comment]
Can we agree that we should have those three options:

* annotation processor (runtime)
* be created by the application developer (manually)
* the metamodel can be accessed dynamically (using reflection)

**Comment by njr-11** [comment]
> @njr-11 You are assuming that the user should generate this code; nope, as we have in Jakarta Persistence, the provider, not the developer, should create this code.
...
> About the encapsulation, you are right; it should be public static volatile ...

I was saying it must either be one or the other.  By confirming the you wanted `public static volatile` which was not in the examples, that means the user does not need to access generated code.  However, please closely read my comments about `static volatile` with regard to the goal/concern number 1 that you raised, and confirm that you are okay with intentionally introducing that vulnerability, which is what we are doing by switching to `static volatile`.

**Comment by otaviojava** [comment]
> > @njr-11 You are assuming that the user should generate this code; nope, as we have in Jakarta Persistence, the provider, not the developer, should create this code.
> > ...
> > About the encapsulation, you are right; it should be public static volatile ...
> 
> I was saying it must either be one or the other. By confirming the you wanted `public static volatile` which was not in the examples, that means the user does not need to access generated code. However, please closely read my comments about `static volatile` with regard to the goal/concern number 1 that you raised, and confirm that you are okay with intentionally introducing that vulnerability, which is what we are doing by switching to `static volatile`.

Yes, thank you for raising that; the current encapsulation is fine; let´s keep it as we have it now:
`public static final`

About the flavors, can we agree on those three flavors:

* annotation processor (runtime)
* be created by the application developer (manually)
* the metamodel can be accessed dynamically (using reflection)

If yes, I can open a PR and take some inspiration from the Jakarta Persistence to make everybody happy.

**Comment by njr-11** [comment]
Yes, we should aim to allow for both runtime and dynamic approaches to be taken on the part of the provider.  I don't see why is should be a goal to let the application developer manually create the StaticMetamodel if that's what you are suggesting, so I would leave that middle one out as a goal.

**Comment by otaviojava** [comment]
Good point, thus, I will put the manual one as a low priority here.

**Comment by njr-11** [comment]
It's fine that you are looking for ways to further improve on the design here.  I do want to emphasize that as best I can tell the current design is already compatible with both compile-time and dynamic solutions, whichever the Jakarta Data provider chooses.  I provided detail earlier on one way it can be achieved dynamically, which I tried out to confirm.  In the case of compile-time, I think the provider would just need to generate a line of code per `Attribute` to invoke `init` on it, passing in an AttributeInfo instance that doesn't need to be generated, but could be if the provider wanted to.

**Comment by otaviojava** [comment]
Thank you for all the help, Nathan; you are amazing!

I will change a little to using what is in the market and works: the Jakarta Persistence. Also, we agree to keep compatibility with both specs.

I will create the PR to make it easier to read and review.

**Comment by njr-11** [comment]
Please explain in terms of the API that is currently available exactly what is broken without doing what you suggest.  I understand that we could add information such the Element type for a Collection.  I imagine that will be useful in the future, but it is completely unclear how the API is currently broken without it.  The same applies for some of these other bullet points.  You talk about needing to know the key and value for a MapAttribute.  And again, that sort of thing seems like it could possibly be useful in the future, but it is unclear where the API is currently broken without it.  I have no idea what you mean by "There is also the Heritage point that we need to cover."

The Jakarta Data API currently only needs the static metamodel to compose `Sort` instances in a type-safe manner.  All we should be aiming to do for version 1.0 is to cover that much, and to do it without preventing the addition of other aspects to the static metamodel in the future.  Given that we don't allow sorting entities based on a Collection attribute or a Map attribute (the spec doesn't even define Map attributes at all) I can't see why any of this is blocking us.  With this pull, we have the Attribute interface for the static metamodel and it is extensible for the future where we can define other more specific non-sortable types and the detail that goes with them in a future version of the spec.

**Comment by otaviojava** [comment]
My biggest concern is time and fixing more bugs.

Once we have a limited resource, timing: I recommend prioritizing what we have on our plate, and it is close to finishing and holding this feature.

We have the most critical one, as you point out here: https://github.com/jakartaee/data/pull/317.

At StaticMetamodel, we are delivering just the Sort, and there is a risk that what we are creating won't be compatible with Criteria; furthermore, it is not compatible with Jakarta Persistence. 

My recommendation would hold it for two reasons:

* Time priority: focus on the other points that are a must to go, such as queries and documentation adjustments.
* The risk: it is safer to deliver both sort and query criteria together; furthermore, check the compatibility with JPA, as we agree with Gavin King.

**Comment by njr-11** [comment]
You are wrong about saying that what we have for the static metamodel is not compatible with Jakarta Persistence.  That's what I've been trying it out against and it works very well.

In any case, it's perfectly valid to defer the static metamodel to the next version if you have worries about unforeseen problems that might arise.  Although I believe that this pull fixes the remaining problem, I would be fine with deferring the static metamodel until the next version.  Applications can just use their own constants in the mean time.  The person you need to get agreement from on deferring it out of version 1.0 is Gavin, who is the one who was asking for it to be included.

**Comment by otaviojava** [comment]
> You are wrong about saying that what we have for the static metamodel is not compatible with Jakarta Persistence. That's what I've been trying it out against and it works very well.
> 
> In any case, it's perfectly valid to defer the static metamodel to the next version if you have worries about unforeseen problems that might arise. Although I believe that #316 fixes the remaining problem, I would be fine with deferring the static metamodel until the next version. Applications can just use their own constants in the mean time. The person you need to get agreement from on deferring it out of version 1.0 is Gavin, who is the one who was asking for it to be included.

Done.

I talked with Gavin, so we can proceed to create a tag and remove this for a while.

**Comment by njr-11** [comment]
Closing because StaticMetamodel was removed from version 1.
