### ISSUE TITLE
Issues at the spec documenation about Ketset

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#332]
### Specification Version

1.0.0-M1

### Bug report

We need to check the consistency of the documentation about this topic. For example:

> You can obtain the next page with,
>
>for (Pageable p = Pageable.ofSize(50); p != null; ) {
 > page = customers.findByZipcodeOrderByLastNameAscFirstNameAscIdAsc(55901, p);
>  ...
>  p = page.nextPageable();
>}

However, checking th code it returns a [OFFSET](https://github.com/jakartaee/data/blob/main/api/src/main/java/jakarta/data/page/Pageable.java#L72-L74)

### Additional information

We need to guarantee a better expirience and making the API more consistence even with we need to break it in two classes again.

**Comment by njr-11** [comment]
There doesn't appear to be anything wrong with the example you cited.  You can start off by reading from an offset and switch over to keyset-based pagination for subsequent pages as this is doing.  It's very useful when the application wants to start at the very beginning position, and then relative to the cursor/keyset from there.

**Comment by otaviojava** [comment]
Thank you, I got it.
