### ISSUE TITLE
Review the Spec for conciseness

### ISSUE THREAD

**Issue by mswatosh** [jakartaee/data#353]
With my last build, the Spec is currently at 47 pages! It's amazing how far the spec has come over the last year, and given that there are more ideas being planned for the next version of Jakarta Data, the spec will only continue to grow. Given that, I think it's important that we keep the spec concise where we can, so it remains manageable for future versions.

- [ ] Section 1
- [ ] Section 2
- [ ] Section 3
- [ ] Section 4
- [ ] Section 5

**Comment by otaviojava** [comment]
@mswatosh can we close this one?

**Comment by mswatosh** [comment]
Not yet, sorry I haven't had a chance to review this. I'll try to get to it soon

**Comment by gavinking** [comment]
@mswatosh I happen to agree that there's currently a fair bit of repetition in the spec, including quite a lot of throat-clearing at the beginning.

Overall the spec is now quite well-written, so this doesn't bother me as much as it did before, and I don't think it's a critical issue, but, that said:

- I wonder if chapters 1 and 2 could be merged into a single chapter, and possibly condensed a little.
- I wonder if chapters 5, 6, and 7, being very short, could be reorganized as a single chapter (or possibly as two chapters), and reviewed for repetition.

WDYT?

**Comment by KyleAure** [comment]
Closing issue as completed for the Jakarta Data 1.0 milestone
