### ISSUE TITLE
Return type of Page (and Slice) for repository methods

### ISSUE THREAD

**Issue by njr-11** [jakartaee/data#36]
**Description**

As a:

- [ ] Application user/user of the configuration itself
- [x] API user (application developer)
- [ ] SPI user (container or runtime developer)
- [ ] Specification implementer

...I need to be able to:
define repository methods that return a Page of results

...which enables me to:
more efficiently work with paginated data.

Several of the existing implementations ([Spring Data](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Page.html), [Micronaut](https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/model/Page.html), [Jakarta NoSQL](http://www.jnosql.org/javadoc/jakarta/nosql/mapping/Page.html)) have a `Page<T>` interface for working with pages of data.  In the case of the first two, a distinction is made between a `Slice` and a `Page`, with the latter adding in a total count of available results and pages, which avoids collecting the expensive count information when unnecessary.  As pointed out in the comment from @odrotbohm, determination of the count cannot be deferred until the `getTotal*` methods are invoked because it cannot be assumed that resources continue to be available beyond the return of the repository method. 

In any case, I'm opening this issue to consider if Jakarta Data should also have `Page` and `Slice` interfaces to be used as a result type for repository methods, and if so, to consider what it will include from the existing implementations or otherwise.

Here is some initial analysis:

In Spring and Micronaut, a `Page` is [Iterable](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Iterable.html), which seems nice to be able to write code like `for (Product p : page) ...` without needing to convert the page to another type.

It looks like Spring and Jakarta NoSQL have a way to directly obtain a [Stream](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Stream.html) from a `Page`, although otherwise a stream could be obtained indirectly.

Spring and Micronaut have the ability to obtain the next and previous Pageable (page request information).
All 3 have a way to obtain the Pagination/Pageable information for the current page, which can be used to compute the next and previous page information.
Jakarta NoSQL has a method to directly obtain the next page, but this would require resources to continue to be available beyond the end of the repository method, which as stated earlier is not something that is possible for at least one of the existing implementations.

Spring and Micronaut have a `getNumberOfElements` method which seems useful for identifying how many results can be obtained from the page and for quickly identifying when a page is empty and so there are no more.
To go along with this a `page.get(index)` to access a result on the page without needing to convert the page seems like it might also be useful, although I don't see that anywhere.

Spring and Micronaut have a `getSort` method.  If this is useful, it should be noted that the sorting for pagination could come from an `OrderBy...` as well as `Sort`, but the former could easily be converted so that we could still return a meaningful value from a `getSort` method.

Spring and Micronaut have a `map` function for obtaining the page with a mapping function applied to transform results.

Spring and Micronaut have a `getContent` method for obtaining the page as a `List<T>`, whereas Jakarta NoSQL has a `getContent` method that accepts a Collection supplier, enabling you to obtain the page as any collection type, for example, `page.getContent(ArrayList::new)`

**Comment by odrotbohm** [comment]
A couple of comments:

> … although it isn't immediately clear to me why collection of that information couldn't just be deferred until the getTotal* methods are invoked.

Because when the `Page` is returned from the repository, you cannot assume any resources being available anymore to query for the total. Also, it would require the original query to be kept around, as that would have to be augmented to result in a count projection. Count query can become significantly expensive on certain data stores and often pagination is used as a form of "batched streaming", so that being able to navigate forward through pages is enough. That's why `Slice` exists. The queries issued to obtain a slice simply read one element more than asked for through the `Pageable` and, the presence or non-presence of the additional element indicates, whether a next slice is available.

> It looks like Spring and Jakarta NoSQL have a way to directly obtain a [Stream](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Stream.html) from a Page, although otherwise a stream could be obtained indirectly.

Spring Data's `Page` implements `Streamable`, an extension of `Iterable` that exposes a `stream()` method defaulting to non-parallel streaming.

> Jakarta NoSQL has a method to directly obtain the next page.

I would recommend avoiding that. If a `Page` is returned from a repository method, it has to have it's content and metadata populated. Any subsequent operation that would have to access the underlying data store would require to keep resources held available, connections open etc. without a clear boundary when to release them (same rationale as with the `….getTotal*()` methods above). That's why the interaction pattern in Spring Data has been: create a `Pageable`, obtain a `Page` via the repository, use the navigation abilities on the `Pageable` attached to that to request further `Page`s from the repository.

> Spring and Micronaut have a getSort method, which I don't think we will need because we've decoupled Sort from Pageable.

Can you elaborate on that? Paging without sorting doesn't really make sense, as without stable sorting, the page results (navigating through pages) cannot be assumed stable.

**Comment by keilw** [comment]
@odrotbohm Sorting in particular is another issue #21 and please vote on that ticket or comment there to help others cast their vote.

**Comment by njr-11** [comment]
@odrotbohm Thanks for all of the insights and background that you provided, especially on the requirement to have separation between usage of Page and access to resources.  I'll update the main issue description and title updated based on your comments.

> Can you elaborate on that? Paging without sorting doesn't really make sense, as without stable sorting, the page results (navigating through pages) cannot be assumed stable.

Oops, I didn't mean to say pagination without sorting.  I was only questioning the reason for `Sort Page.getSort()` given that the sorting might have come from a `findBy...OrderByOneThingAscAnotherThingDesc(..., Pageable)` repository method name rather than a `Sort`.  It's not a problem though.  If `Page.getSort()` is useful, an `OrderBy...` could easily be converted to it.  I'll clarify my comment there so it doesn't look like I'm proposing nonsensical unordered paging.

**Comment by odrotbohm** [comment]
@njr-11 – Thanks for the clarification. It's indeed useful to be able to create a standalone `Sort` instance. Spring Data derives them from the method name (see `PartTree` for details), and then simply adds the `Sort` instance potentially given parameter by calling the `….and(…)` method on the originally, derived from the method instance.

**Comment by njr-11** [comment]
Given that many of the existing implementations have [getContent](https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/model/Slice.html#getContent()) and [toList](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/util/Streamable.html#toList--) methods for accessing a Page<T>/Slice<T> as a `List<T>` and they also have methods of Page/Slice that overlap what List provides, such as [getSize](https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/model/Slice.html#getSize())/[getNumberOfElements](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Slice.html#getNumberOfElements--) and [iterator](https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/model/Slice.html#iterator()) and [stream](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/util/Streamable.html#stream--) and [isEmpty](https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/model/Slice.html#isEmpty()), I would be in favor of having the Page/Slice interface(s) in Jakarta Data directly extend `java.util.List<T>`.  Java provides AbstractList, which allows for easy creation of an unmodifiable List by minimally providing just `get` and `size` so it seems like it would be minimal work to achieve this.  It would eliminate an extra method call for users and potentially eliminate unnecessary object creation as well.

**Comment by odrotbohm** [comment]
I'd strongly recommend against this, as a `Page` simply is not a `List` in the first place. Plus, none of the modifying operations make sense on a `Page`. It's a dedicated abstraction *apart* from a `List`.
