### ISSUE TITLE
[Bug]: API artifact doesn't match naming conventions of all other Jakarta EE artifacts

### ISSUE THREAD

**Issue by lprimak** [jakartaee/data#361]
### Specification Version

1.0.0-M1

### Bug report

> Description of the bug found.

Currently, Data API GAV is `jakarta:jakarta-data-api`

However, all other artifacts are like this: `jakarta:jakarta.websocket-api`
Take note of a dash instead of a dot.
This should be changed to `jakarta:jakarta.data-api`

This interferes with Javadoc production on the umbrella spec.
This should be renamed

**Comment by lprimak** [comment]
cc: @ivargrimstad

**Comment by ivargrimstad** [comment]
Thanks @lprimak!
I think we can live with the workaround in https://github.com/jakartaee/jakartaee-api/pull/146 for M1, but it should be fixed for the next release. It would be confusing if there were two 1.1.0-M1s in Maven Central.

**Comment by lprimak** [comment]
This is now fixed.
