### ISSUE TITLE
Artifact name standardization

### ISSUE THREAD

**Issue by KyleAure** [jakartaee/data#379]
I noticed when making the M2 release as part of #356
That the API artifact was renamed from `jakarta-data-api` to `jakarta.data-api` in #362

Should we update all of our artifacts to follow this same naming convention?

```
jakarta-data-parent -> jakarta.data-parent 
jakarta-data-spec -> jakarta.data-spec
jakarta-data-tck-dist -> jakarta.data-tck-dist
jakarta-data-tck -> jakarta.data-tck
```

I think if we were going to do this M2 would be a perfect time.
FWIW - I do not like using the period (.) as it goes against [maven convention](https://maven.apache.org/maven-conventions.html) of using all hyphens (-).  But I'd rather have them all the same.

**Comment by njr-11** [comment]
Looking at other Jakarta specs, the . appears to be the convention used across those, so yes, we should update them to all be the same.
