### ISSUE TITLE
[Bug]: At Update annotation, should we be most restrict

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#403]
### Specification Version

1.0.0-M2

### Bug report

At the [Update](https://github.com/jakartaee/data/blob/main/api/src/main/java/jakarta/data/repository/Update.java) annotation, we have this quote:

> The return type of the annotated method must be {@code void}, {@code boolean}, a numeric primitive type
> * (such as {@code int}), a corresponding primitive wrapper type (such as {@link Integer}), or the same type as the parameter.

Should we allow all primitives?
Why return the result as float, double, or byte?

IMHO: It should be most metric, such as only int and long

**Comment by njr-11** [comment]
I agree. Including double and float is unnecessary here.
