### ISSUE TITLE
[clarification]: When implement method by query vs Parameter-based query method 

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#405]
### Specification

https://github.com/jakartaee/data/blob/main/spec/src/main/asciidoc/repository.asciidoc#parameter-based-automatic-query-methods

### I need clarification on ...

This point is unclear: when should I use one instead of another?

When this is a syntax issue of  [query by method](https://github.com/jakartaee/data/blob/main/spec/src/main/asciidoc/repository.asciidoc#query-by-method-name) and when this is an [parameter macher](https://github.com/jakartaee/data/blob/main/spec/src/main/asciidoc/repository.asciidoc#parameter-based-automatic-query-methods).

Shall we have an annotation to explicitly say this Parameter-based query method and keep only the method by query an exception?

```java
@Find
Book bookByIsbn(String isbn);
@Find
List<Book> booksByYear(Year year, Sort order, Limit limit);
@Find
Page<Book> find(@By("year") Year publishedIn,
                @By("genre") Category type,
                Pageable pagination);
```

**Comment by njr-11** [comment]
The JavaDoc states the rules for interpretation very clearly,

> **Precedence of Repository Methods**
> 
> The following precedence, from highest to lowest, is used when interpreting the meaning of repository methods.
>
>    1. If you define a method as a Java default method and provide implementation, then your provided implementation is used.
>    2. If you define a method with a Resource Accessor Method return type, then the method is implemented as a Resource Accessor Method.
>    3. If you annotate a method with [Query](file:///Users/njr/lgit/data/api/target/apidocs/jakarta.data/jakarta/data/repository/Query.html), then the method is implemented to run the corresponding Query Language query.
>    4. If you annotate a method with an annotation that defines the type of operation ([Insert](file:///Users/njr/lgit/data/api/target/apidocs/jakarta.data/jakarta/data/repository/Insert.html), [Update](file:///Users/njr/lgit/data/api/target/apidocs/jakarta.data/jakarta/data/repository/Update.html), [Save](file:///Users/njr/lgit/data/api/target/apidocs/jakarta.data/jakarta/data/repository/Save.html), or [Delete](file:///Users/njr/lgit/data/api/target/apidocs/jakarta.data/jakarta/data/repository/Delete.html)), then the annotation determines how the method is implemented.
>    5. If you annotate any of the method parameters with a data access related annotation, then Parameter-based Conditions determine the implementation of the method.
>    6. If you define a method according to the Query by Method Name pattern naming conventions, then the implementation follows the Query by Method Name pattern.
>    7. Otherwise, Parameter-based Conditions determine the implementation of the method. You must compile with the -parameters compiler option that makes parameter names available at run time.

However, this information might be missing from the specification document itself.  I will check and open a pull to add it if it is not already there.
