### ISSUE TITLE
[clarification]: Should we put more restriction at the non-bult-in repositories?

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#417]
### Specification

https://github.com/jakartaee/data/blob/main/spec/src/main/asciidoc/repository.asciidoc

### I need clarification on ...

In the context of our repository structure, we currently have two distinct types: built-in repositories that provide predefined interfaces (BasicRepository, PageableRepository, CrudRepository), and non-built-in repositories where developers have more flexibility to code as they see fit. This issue is somewhat similar to the annotation returning various numeric primitive and wrapper types, raising questions about whether replacing a count with double and long formats makes sense. (Reference: [link to the related issue](https://github.com/jakartaee/data/issues/403))

The central question is whether we should impose restrictions on repository design in our domain-centric approach.

Proposed Solution:
In my humble opinion (IMHO), we should aim to avoid repositories like the one shown below in our API:

```java
@Repository
AnyInteractionRepository {

    List<Animal> findByName(String name);

    List<Car> findByPlate(String plate);

    List<Person> findByAge(int age);
}
```

### Additional information

One potential solution would be to encourage developers to extend the DataRepository interface or implement certain restrictions to maintain a consistent repository approach, as demonstrated below:

```java
@Repository
Zoo extends DataRepository<Animal, String> {

    List<Animal> findByName(String name);

    // Should generate a runtime or build-time issue
    List<Car> findByPlate(String plate);
}
```

**Comment by gavinking** [comment]
I don't understand. What is wrong with that code?

**Comment by njr-11** [comment]
Otavio, I don't see why the following from your example would generate an error,

> ```java
>     // Should generate a runtime or build-time issue
>     List<Car> findByPlate(String plate);
> ```

The only difference I see between the example repositories that you have is that the second defines a primary entity type whereas the first does not.  The primary entity type is what to fall back to when a method on the repository doesn't identify any entity type.  For example,

```
   void deleteByName(String name);
```

Having a primary entity type does not prevent you from writing methods that use other entities.  The spec only says that it disambiguates when it is unclear which entity type to use.

**Comment by njr-11** [comment]
I might have misunderstood. Maybe you are indicating that you want to add language to the specification that would cause that scenario become an error. I don't see why we should add a restriction that makes it into an error. Given that multiple entity types are supported as in the first example, it seems reasonable that you should be able to define a primary entity type that can disambiguate when you are using multiple entity types just like you can when there is a single entity type used.  Changing this would mean going out of our way to make things more difficult for a subset of users for no apparent benefit.

**Comment by otaviojava** [comment]
> I don't understand. What is wrong with that code?


Given this method:

```java
@Delete
void deleteByName(String name);
```

How do I know the entity?

**Comment by gavinking** [comment]
OK, right, so I agree that those method signatures don't make sense unless the repository has a well-defined primary entity.

**Comment by njr-11** [comment]
> But, once we don't have this Entity parameter, or any restriction. What should we do when we have this:
> 
> ```java
> void deleteByName(String name);
> long counbByName(String name);
> boolean existByName(String name);
> ```
> 
> With a type, I know where to find, in that case, I don't know.

Jakarta Data has quite a bit of documentation on this already, stating that you must define a primary entity type if you want to use methods that do not define a entity type in the method signature.

From JavaDoc:
```
 * <h2>Identifying the type of Entity</h2>
 *
 * <p>Most repository methods perform operations related to a type of entity. In some cases,
 * the entity type is explicit within the signature of the repository method, and in other
 * cases, such as {@code countBy...} and {@code existsBy...} the entity type cannot be determined
 * from the method signature and a primary entity type must be defined for the repository.</p>
 *...
 * <b>Identifying a Primary Entity Type:</b>
 *
 * <p>The following precedence, from highest to lowest, is used to determine a primary
 * entity type for a repository.</p>
 *
 * <ol>
 * <li>You can explicitly define the primary entity type for a repository interface
 * by having the repository interface inherit from a super interface such as
 * {@link CrudRepository} where the primary entity type is the type of the
 * super interface's first type parameter. For example, {@code Product}, in,
 * <pre>
 * &#64;Repository
 * public interface Products extends CrudRepository&lt;Product, Long&gt; {
 *     // applies to the primary entity type: Product
 *     int countByPriceLessThan(float max);
 * }
 * </pre>
 * </li>
 * <li>Otherwise, if you define life cycle methods ({@link Insert}, {@link Update},
 * {@link Save}, or {@link Delete}) where the method parameter is a type, an array of type,
 * or is parameterized with a type that is annotated as an entity,
 * and all of these methods share the same entity type,
 * then the primary entity type for the repository is that entity type. For example,
 * <pre>
 * &#64;Repository
 * public interface Products {
 *     &#64;Insert
 *     List&lt;Product&gt; add(List&lt;Product&gt; p);
 *
 *     &#64;Update
 *     Product modify(Product p);
 *
 *     &#64;Save
 *     Product[] save(Product... p);
 *
 *     // applies to the primary entity type: Product
 *     boolean existsByName(String name);
 * }
 * </pre>
 * </li>
 * </ol>
```

And also in the spec,
> For `count`, `exists`, and other `delete` methods that do not return the entity or accept the entity as a parameter, the entity type cannot be determined from the method signature and a primary entity type must be defined for the repository.
> 
> Users of Jakarta Data declare a primary entity type for a repository by inheriting from a built-in repository super interface, such as `BasicRepository`, and specifying the primary entity type as the first type variable. For repositories that do not inherit from a super interface with a type parameter to indicate the primary entity type, life cycle methods on the repository determine the primary entity type. To do so, all life cycle methods where the method parameter is a type, an array of type, or is parameterized with a type that is annotated as an entity, must correspond to the same entity type. The primary entity type is assumed for methods that do not otherwise specify an entity type, such as `countByPriceLessThan`. Methods that require a primary entity type raise `MappingException` if a primary entity type is not provided.

The primary entity type is also mentioned in various other places in the JavaDoc.

It looks to me like the specification already has all of this well defined. It even states which error to raise when a primary entity type is needed but not defined.  If any part of it is unclear, we can improve it.

**Comment by gavinking** [comment]
> > I don't understand. What is wrong with that code?
> 
> Given this method:
> 
> ```java
> @Delete
> void deleteByName(String name);
> ```
> 
> How do I know the entity?

Do be clear, the Javadoc of `@Delete` states:

> The `Delete` annotation indicates that the annotated repository method requests one or more entities to be removed from the database. To request deletion of specific entity instances, the annotated repository method must have a single parameter whose type must be one of the following:
> - The entity to be deleted.
> - An Iterable of entities to be deleted.
> - An array of entities to be deleted.

And the spec already says:

> For repository methods that are annotated with `@Insert`, `@Update`, `@Save`, or `@Delete`, the entity type is determined from the method parameter type.  For `find` and `delete` methods where the return type is an entity, array of entity, or parameterized type such as `List<MyEntity>` or `Page<MyEntity>`, the entity type is determined from the method return type.  

So I think these and similar cases are covered.


> What should we do when we have this:
>
>    void deleteByName(String name);
>    long counbByName(String name);
>    boolean existByName(String name);
> 
> With a type, I know where to find, in that case, I don't know.

The spec says:

> For `count`, `exists`, and other `delete` methods that do not return the entity or accept the entity as a parameter, the entity type cannot be determined from the method signature and a primary entity type must be defined for the repository.


Which I guess about covers it?

**Comment by otaviojava** [comment]
Yes, we covered.
thank you.
