### ISSUE TITLE
Documentation Improvement: Explaining Embedded Data in Jakarta Data [clarification]

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#463]
### Specification

https://github.com/jakartaee/data/pull/461

### I need clarification on ...

We are currently working on improving the documentation for Jakarta Data. One area that needs attention is embedded data, specifically in the context of NoSQL and relational databases. Managing embedded data is an important aspect of data modeling and manipulation, and providing more precise explanations and examples will be beneficial for developers working with Jakarta Data.

### Additional information

**Areas for Improvement:**

1. **NoSQL Embedded Data:**
   - Provide detailed explanations of embedding data within NoSQL databases.
   - Clarify the concept of embedding data and its significance in NoSQL database design.
   - Include examples illustrating both grouping and flat types of embedded data.
   
2. **Relational Database Embedded ID:**
   - Explain the concept of an embedded ID in relational databases.
   - Provide examples demonstrating the use of composite primary keys composed of multiple attributes.
   
3. **ID and Sort in Jakarta Data:**
   - Clarify the role of the `ID` attribute in Jakarta Data entities.
   - Explain how sorting works in Jakarta Data and its importance in query results.

**Comment by gavinking** [comment]
@otaviojava what is the status of this? It looks to me like most of these things are done.

The one thing here we don't talk about, if I recall correctly is:

> Relational Database Embedded ID:
>
> - Explain the concept of an embedded ID in relational databases.
> - Provide examples demonstrating the use of composite primary keys composed of multiple attributes.

But I'm not sure how much we really need to say about this. I feel like the JPA spec says it, and that's more where it belongs.

But perhaps you're thinking of something more specific that I'm missing.

**Comment by otaviojava** [comment]
It is done; I will close this one.
