### ISSUE TITLE
[clarification]: naming of interfaces supporting key-based pagination

### ISSUE THREAD

**Issue by gavinking** [jakartaee/data#504]
### Specification

KeysetAwareBlahBlah

### I need clarification on ...

whether we can find better names.

### Additional information

So to me there's multiple things that aren't ideal with `KeysetAwarePage`/`KeysetAwareSlice`:

1. I'm not sure why it's a "set" of keys. To me, key-based pagination works on the basis of _a_ unique key of the query result set. Sure, it might be a composite key, but it's definitely nonstandard to call a composite key a "key set".
2. `FooAware` is usually what you call an abstraction over things that can respond to `Foo` events, or have `Foo` injected, or whatever. It seems inappropriate here.
3. The `Page` as a special kind of `Slice` thing is just weird to me, since `Slice` is quite clearly the type which represents a page of results, and `Page` is just a specialization of that which tells you how many other pages it has in its gang. To see that there's nothing logical in this naming convention, ask yourself if it would come out any worse if we simply _reversed the polarity of the names_ and called pages `Page`s and pages-with-totals `Slice`s. I think it's exactly the same bad, not worse.
4. Putting it all together, `KeysetAwareSlice` is just not a snappy name of something that the repository _client_ is going to be passing around. It sounds very technical.
5. IntelliJ thinks "keyset" is a spelling error.

So, who has some alternative ideas?

I'll go first: I would change `KeysetAwarePage` to `KeyedPage` or `KeyBasedPage`.

I don't have any useful suggestions for the `Page` vs `Slice` thing, which might mean we're stuck with `Slice`. The best I can come up with is `Page` vs `PageWithTotal`, and then `KeyBasedPageWithTotal` is just 🤮. On the other hand, _at least it actually describes what it is._

Thoughts? Suggestions?

**Comment by gavinking** [comment]
Hurm, `Range` is probably a better word than `Slice`.

**Comment by gavinking** [comment]
`Window`?

**Comment by gavinking** [comment]
> `Window`?

This is non-terrible, actually. It's better than `Slice` at least.

**Comment by gavinking** [comment]
> The `Page` as a special kind of `Slice` thing is just weird to me, since `Slice` is quite clearly the type which represents a page of results, and `Page` is just a specialization of that which tells you how many other pages it has in its gang.

Ugh, it's actually worse than this, since `Slice` is actually the type which declares all the operations involving `PageRequest`s. That is to say, they're actually `SliceRequest`s :-(

**Comment by gavinking** [comment]
> `CursorBasedPage`

I don't hate this. `Cursor` is certainly better that `KeysetAware`.

> Another aspect to think about is why we even have a `Slice` type at all.

Yeah, I almost posted that too, but I didn't want to scare people away from the discussion. 

Both before and after having implemented all this, the current design seemed and still seems somewhat overcomplex to me, for what it does, and I would be prepared to sacrifice some niceties to simplify it.

> If we do this, we would need to specify that `Page.totalPages()` and `Page.totalElements()` must raise `UnsupportedOperationException` when the total is not requested to be obtained.

I do not love the loss of typesafety, obviously, but in this case I think it might be a tradeoff worth making.

**Comment by gavinking** [comment]
You could even called it `CursoredPage`. The beauty of my native tongue is the permission to freely verb nouns.

**Comment by gavinking** [comment]
And for free you get that it sounds almost exactly like `CursedPage` when spoken out loud, which is a definite plus for that option.

**Comment by njr-11** [comment]
> You could even called it `CursoredPage`. The beauty of my native tongue is the permission to freely verb nouns.

`CursoredPage` is also good.  I think that will be just as well understood as `CursorBasedPage`.

**Comment by gavinking** [comment]
> Suppose we removed `Slice` completely and added a `countTotal`(true/false) field to the `PageRequest` indicating whether to fetch the page count,
>
> ```
> Page<Employee> slice = employees.findAll(PageRequest.ofSize(20).countTotal(false).sortBy(...));
> ```

This proposal is definitely growing on me.

> If we do this, we would need to specify that `Page.totalPages()` and `Page.totalElements()` must raise `UnsupportedOperationException` when the total is not requested to be obtained.

Probably more of an `IllegalStateException` but that's a detail.

**Comment by gavinking** [comment]
A point probably in favor of doing this is also that it lets you decide how often the total should be "refreshed". With the current design, my interpretation is that you're supposed to refresh the `totalElements()` count _every time you fetch a new page_. But that's almost always excessive. It seems like something you would typically to do once, for the first page. Your proposal gives the client easy control over that, whereas the static return type doesn't.

**Comment by gavinking** [comment]
Another point in favor: _if_ at some point in the future, we were to decide that this change was a mistake, we could _easily_ reintroduce `Slice` as a super type of `Page`, just like what we have today, and deprecate the `.countTotal()` method, without breaking anything.

**Comment by gavinking** [comment]
This is mostly done by #517, and by the bugfixes #521 and #524 from @njr-11.

One minor outstanding thing is to get rid of the phrase "keyset".

**Comment by gavinking** [comment]
With #525, this is done, from my perspective.
