### ISSUE TITLE
Status of component spec deadline extension

### ISSUE THREAD

**Issue by njr-11** [jakartaee/data#516]
Ed Burns/Jakarta EE Platform has confirmed an agreement to extend Jakarta Data's deadline for component specification release review in order to allow Jakarta Data to include a Query Language subset (being worked on in #458).

The deadline extension has been granted under the following conditions, which the Jakarta Data committers and participants must now adhere to for the agreement to remain valid:

* All the stakeholders agree the extension is just to accommodate inclusion of JPQL subset query.
* The schedule extension is not to be interpreted as open season on new features to make it into 1.0.
* The schedule extension does not increase the risk of not achieving “June/July EE 11 done”.
* Data 1.0 is in a unique position to be granted an exception because no other specs depend on it.

Specifically, the Jakarta Data committers and other specification participants will:

- [x] Define the Jakarta Data Query Language as a subset of JPQL.
- [x] Author TCK tests for the Query Language.
_This is currently in progress._
- [x] For other work that is in progress, if not agreed on by committers and merged by 2024-03-08, then it must be deferred to Future.
- [x] Defer all other issues/pulls to Future (including those which have not yet been opened) in order to focus on getting the Query Language and its TCK complete.
_In the days leading up to the Jakarta Data meeting on 2024-03-20, some participants have stopped abiding by this requirement, stating on that meeting that they will make whatever changes and alterations they believe are good for the spec regardless of their relation to the Query Language subset._
- [x] Have all of the TCK tests passing by 2024-04-19.
- [x] Agree to create a Jakarta Data 1.0 release candidate by 2024-04-19.
- [x] Remaining time to be used for at least one published compatible implementation to be available in minimum alpha form.
- [x] Submit for component specification release review for 2024-05-31.

**Comment by KyleAure** [comment]
Closing issue as completed for the Jakarta Data 1.0 milestone
