### ISSUE TITLE
[clarification]: descending @OrderBy

### ISSUE THREAD

**Issue by gavinking** [jakartaee/data#545]
### Specification

`@OrderBy` annotation

### I need clarification on ...

whether it would be better to have `@Ascending` and `@Descending` annotations.

### Additional information

I find myself with stuff like this:

```java
@Find
@OrderBy("title")
@OrderBy(value = "isbn", descending=true)
List<Book> books();
```
The `@OrderBy` annotation looks much nicer when you have ascending order than when you have descending order.

And there's a sort-of offensive asymmetry there.

An alternative would be:
```java
@Find
@Ascending("title")
@Descending("isbn")
List<Book> books();
```
It's just an idea; something to consider.

**Comment by beikov** [comment]
I don't think this will work because there is no ordering across different annotations. With a single annotation, the ordering is ensured through the repeatable container annotation.

**Comment by gavinking** [comment]
> I don't think this will work because there is no ordering across different annotations. With a single annotation, the ordering is ensured through the repeatable container annotation.

Ah. Good point. Didn't think of that.

OK, so I will just close this.
