### ISSUE TITLE
[clarification]: Clarification on Handling Embedded Types in Metamodel Generation

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#559]
### Specification

https://github.com/jakartaee/data/blob/main/spec/src/main/asciidoc/repository.asciidoc#type-safe-access-to-entity-attributes

### I need clarification on ...

Hello,

I've been exploring the metamodel specifications and have encountered a scenario requiring further clarification regarding handling embedded types during generation. Specifically, I am concerned about the disambiguation mechanism (if any) for embedded types used across different entities.

To illustrate, consider the following Java classes:

```java
@Entity
public class Person {
    @Id
    private String id;
    @Column
    private String name;
    @Column
    private Address address; // Embedded Address
}

@Entity
public class Order {
    @Id
    private UUID id;
    @Column
    private String name;
    @Column
    private Address delivery; // Another instance of Embedded Address
}

@Embedded
public class Address {
    private String city;
}
```

In the example above, both `Person` and `Order` entities contain an embedded `Address` type. My question revolves around how the metamodel generation process distinguishes between these two instances of the `Address` class. Is there a specific mechanism to handle such cases of embedded types to avoid ambiguity? What best practices should be followed to ensure that the metamodel remains clear and consistent when dealing with embedded types across multiple entities?

**Comment by gavinking** [comment]
Not sure I see where ambiguity could arise. What are you thinking of here?

**Comment by otaviojava** [comment]
Given the same entities of the previous sample:

How do you generate this metadata class?

Mainly because:

```java
var name = _Person.address.city.name():// it must generate "address.city"
var name2 = _Order.delivery.city.name();// it must generate "delivery.city"
```

I mean, if it were a constant, it wouldn't get the proper path:

```java
var name = _Person.Address.city.name():// it must generate "address.city"
var name2 = _Order.Address.city.name();// it must generate "delivery.city"
```

My point is that our spec covers only the basic attributes, but what happens if it is not a basic attribute?

**Comment by gavinking** [comment]
This is also covered in the spec by this bullet point:

> • The name of the field, ignoring case, must match the name of an entity attribute, with the _ character in the field name delimiting the attribute names of hierarchical structures or relationships, such as embedded classes.

**Comment by gavinking** [comment]
[Note that it's a little bit hard to find that, since it's in section 3.1.9.1, but the natural place to look for it is section 3.1.9.4. But it's there.]

**Comment by gavinking** [comment]
@otaviojava yes, I believe so, best check with @njr-11.

**Comment by njr-11** [comment]
> In this case, there is an issue, right?
> 
> It should be:
> 
> ```java
> public static volatile Attribute<Person> name;
> ```

Yes, that's a bug in the documentation. That line of the example is incorrectly leaving out `<Person>`.

**Comment by otaviojava** [comment]
> > In this case, there is an issue, right?
> > It should be:
> > ```java
> > public static volatile Attribute<Person> name;
> > ```
> 
> Yes, that's a bug in the documentation. That line of the example is incorrectly leaving out `<Person>`.

Ok, I will create a PR to fix it.
