### ISSUE TITLE
[clarification]: inheritance from generic superinterfaces

### ISSUE THREAD

**Issue by gavinking** [jakartaee/data#574]
### Specification

Data

### I need clarification on ...

to what extent we really require support for generic repository methods and repository methods inherited from generic superinterfaces.

### Additional information

In the preamble of chapter 4 we say: 

> A repository interface may inherit methods from a superinterface. A Jakarta Data implementation must treat inherited abstract methods as if they were directly declared by the repository interface. 

This is really quite ambiguous as to whether the actual values of type arguments must be substituted into an inherited repository method declaration before "treat[ing] inherited abstract methods as if they were directly declared by the repository interface".

But, one would probably get the impression from the rest of chapter 4 that generic repository method declarations are _not_ supported.

Except that we then say:

> For example, a repository interface may inherit the `CrudRepository` interface defined by this specification.

and `CrudRepository` is very definitely generic, strongly implying that we do indeed need to be able to handle type argument substitution.

Now, the job of correctly substituting actual type arguments in full generality can get way tricker than quite a few other things we threw in the "too hard" basket. For the built-in supertypes `CrudRepository` and `BasicRepository` it's NBD since we're just substituting the primary entity type. But for arbitrary user-written interfaces it could really be way scarier.

Note: I'm not saying it's impossible; it's absolutely possible. I'm not even sure exactly how tricky it is, without sitting down and doing it. But I'm just not sure that this particular thing what we should be spending our time implementing right now.

So, I would like to suggest, that in order to get compatible implementations out the door as fast as possible, we "clarify" that providers are not required to support parameterized user-written repository supertypes.

I do realize that this means that users would not be able to rely on certain things that they probably hope would work, but not _requiring_ something is not the same as prohibiting it, and we could of course add the requirement in a future release, with appropriate limitations if necessary.

WDYT?

**Comment by njr-11** [comment]
We should explicitly state that generic repository method declarations are not supported (except for the built-in BasicRepository/CrudRepository).  If we wanted to support them, it would require a lot more work and more detail in the spec on how it would work, and that is out of scope for version 1.

**Comment by gavinking** [comment]
OK, great, that's a relief. I will send something to that effect.

**Comment by gavinking** [comment]
This is done.
