### ISSUE TITLE
Proposal for Merging `@Param` and `@By` Annotations to Simplify Parameter Binding in Jakarta Data

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#617]
### Specification

https://github.com/jakartaee/data

### I need clarification on ...

In the current Jakarta Data implementation, two different annotations, `@Param` and `@By`, are used for binding query parameters in different contexts. The `@Param` annotation is used alongside the `@Query` annotation to bind parameters for custom queries. Conversely, the `@By` annotation serves a similar purpose but is utilized with the `@Find` annotation for parameter binding in find operations. This differentiation, while functional, introduces unnecessary complexity and redundancy, making the developer experience less intuitive and the codebase more verbose than it needs to be.

### Proposal:

This issue proposes the merger of the `@Param` and `@By` annotations into a single annotation that can be universally applied for parameter binding, regardless of the operation type (custom query or find operation). The unified annotation approach aims to streamline the code, reduce learning curve for new developers, and enhance overall productivity by simplifying the annotation system in Jakarta Data.

### Example of Current Implementation:

```java
@Repository
public interface BookRepository extends BasicRepository<Book, UUID> {

  @Query("where title like :titlePattern")
  List<Book> booksMatchingTitle(@Param("titlePattern") String titlePattern);

  @Find
  List<Book> find(@By("author") String author);
}
```

#### Proposed Implementation:
```java
@Repository
public interface BookRepository extends BasicRepository<Book, UUID> {

  @Query("where title like :titlePattern")
  List<Book> booksMatchingTitle(@Param("titlePattern") String titlePattern);

  @Find
  List<Book> find(@Param("author") String author);
}
```

#### Benefits:

1. **Simplification**: A single annotation for parameter binding simplifies the framework's usability and the code's readability.
2. **Consistency**: Unifying these annotations promotes a more consistent and intuitive approach to parameter binding across different query types.
3. **Developer Productivity**: Reducing the cognitive load and the number of concepts a developer must understand to work effectively with Jakarta Data enhances productivity and accelerates development cycles.

**Comment by gavinking** [comment]
@otaviojava I'm not a fan of making this change, because it sorta conflicts with what I'm proposing to do here: https://github.com/jakartaee/data/issues/546

i.e. in future, I would have `@By` accept JDQL expressions, whereas `@Param` would continue to only specify query parameter names.

**Comment by otaviojava** [comment]
Good point, I will close this one.
