### ISSUE TITLE
[clarification]: Query by name equals operator question

### ISSUE THREAD

**Issue by starksm64** [jakartaee/data#622]
### Specification

src/main/asciidoc/repository.asciidoc

### I need clarification on ...

The 'BNF Grammar for Query Methods' (QBN) section has no equals operator or description of an equals operator either explicitly or implicitly. Without that, I don't see how one can effectively parse a method name like `findByNumTypeOrFloorOfSquareRoot` which currently exists on the `ee.jakarta.tck.data.framework.read.only.PositiveIntegers` TCK interface.

I'm assuming this should be parsed to `where numType = ?1 or floorOfSquareRoot = ?2`, but this should be be dealt with in the QBN section. It seems like the BNF should include an optional Equal operator:

```bnf
<operator> ::= "Contains" | "EndsWith" | "StartsWith" | "LessThan"| "LessThanEqual" | "GreaterThan" | "GreaterThanEqual" | "Between" | "Empty" | "Like" | "In" | "Null" | "True" | "False"| <equal>
<equal> ::= ["Equal"]
```

So that `findByNumTypeOrFloorOfSquareRoot` parses, and could be written more explicitly as `findByNumTypeEqualOrFloorOfSquareRootEqual`.

### Additional information

Augment the BNF grammar to include an optional Equal operator

**Comment by njr-11** [comment]
The equals comparison operation is implicit when no other comparison operator is included.

It is parsable without it.  The `Or` and `And` keywords delimit the conditions,

```
<predicate> ::= <condition> { ("And" | "Or") <condition> }
```

After that, the condition either ends with one of the comparison operators or it does not,
```
<condition> ::= <property> ["IgnoreCase"] ["Not"] [<operator>]
```
If does not end with any of the operators, it is an equals comparison.

**Comment by starksm64** [comment]
I know the grammar parses, but there is no statement in the spec section about Equal being an implicit default. Without that I don't know how you would write a parser short of running into this in the TCK, or just assuming that there has to be an Equal operator.

**Comment by njr-11** [comment]
> I know the grammar parses, but there is no statement in the spec section about Equal being an implicit default. Without that I don't know how you would write a parser short of running into this in the TCK, or just assuming that there has to be an Equal operator.

That's a bug if the spec doesn't say that. We can get it added.
