### ISSUE TITLE
Pageable and friends should be interfaces

### ISSUE THREAD

**Issue by graemerocher** [jakartaee/data#65]
**Description**

The current design has `Pageable` etc. as classes.  This limits the ability the evolve the API in the future IMO and I am wondering why this is the case.

**Comment by njr-11** [comment]
Some things to consider:
- If `Pageable` becomes an interface, who will provide the implementation? We need to allow for the possibility that there are multiple active Jakarta Data providers (maybe one for NoSQL and one for relational databases). It would be unfortunate if we needed to make the API more complex for users to ensure they are getting the `Pageable` instance from the right one.  It seems like we would still want the Jakarta Data spec to provide an implementation to use by default even if it becomes an interface.
- How does the use of a class for `Pageable` versus an interface limit the ability to evolve the API in the future?  I'm not arguing against having an interface, it just isn't clear to me specifically where it is currently limiting which we will want to ensure an interface-based solution addresses.  In the comments to another pull, I pointed out that methods (along with impl that is default) can be added to classes just as methods with default impl can be added to interfaces.

**Comment by njr-11** [comment]
If we switch to an interface with the spec also providing a basic implementation, one way to do it could be something like,
pageable = `Pageable.ofSize(50).page(1).sortBy(...).withKeyset(...)`
where we have a couple of static `of` methods to construct the instances that are provided by the spec,
and keep the `get` methods for accessing values,
and let the other methods be optionally used to configure values in a fluent pattern.
Different providers that wanted to enhance `Pageable` with capability beyond the spec could define their own extensions to the `Pageable` interface along with a provider-specific way to obtain it, which applications would only need to be concerned with if they want the value-add function that goes beyond the spec.
Would this sort of approach work?

**Comment by graemerocher** [comment]
A default implementation can still be provided and created from static methods of Pageable, I don't see that as an issue as you have done in your example above.

And indeed implementations could have provider-specific extensions that go beyond the spec.
