### ISSUE TITLE
Inconsistent Pageable factory methods

### ISSUE THREAD

**Issue by keilw** [jakartaee/data#67]
**Description**

There is an inconsistency among static factory methods in `Pageable`

- of() with various arguments
- page() which is just a convenience wrapper around of()
- size() ditto

IMO better consistency would be reached by calling those:
- ofPage()
- ofSize()

Along the lines of `OptionalofNullable()` or methods like `ofPrefix()`, `ofRational()`, etc. in JSR 385 [MultiplyConverter](https://github.com/unitsofmeasurement/indriya/blob/master/src/main/java/tech/units/indriya/function/MultiplyConverter.java). Mixing the two conventions, even worse because there are `getPage()` and `getSize()` methods easily confused with `page()` or `size()` seems quite bad.

**Comment by njr-11** [comment]
`ofPage` and `ofSize` are being added in #68
Also, in that pull, we had some discussion about the possibility of switching to record style accessor methods for `Pageable`, which is being voted on in #70.  I'm copying the example from that discussion here because this is likely where it would end up being implemented:

```
p = Pageable.ofSize(50)
            .withPage(5)
            .withSorts(Sort.asc("lastName"), Sort.asc("firstName), Sort.asc("id"))
            .afterKeyset(lname, fname, id);
page = p.page();
size = p.size();
sorts = p.sorts();
mode = p.mode();
cursor = p.cursor();
```

**Comment by otaviojava** [comment]
@njr-11, what do you think about removing the "of"?

```java
p = Pageable.size(50)
            .page(5)
            .sort(Sort.asc("lastName"), Sort.asc("firstName), Sort.asc("id"))
            .afterKeyset(lname, fname, id);
```

**Comment by keilw** [comment]
Still makes it easy to confuse `size()` and `page()` with `getSize()` and `getPage()`.

**Comment by njr-11** [comment]
> @njr-11, what do you think about removing the "of"?
> 
> ```java
> p = Pageable.size(50)
>             .page(5)
>             .sort(Sort.asc("lastName"), Sort.asc("firstName), Sort.asc("id"))
>             .afterKeyset(lname, fname, id);
> ```

We don't know the outcome of the vote under #70 yet, but if the decision is made to have record-style accessors, then methods named like `size(s)` and `page(p)` will be needed for that purpose instead.

> If it's `withPage()` or `withSorts()` then why not also call it `withSize()` that would be more consistent.
The distinction here is that `Pageable.ofSize(s)` is a static method of `Pageable` that creates a new instance with all other properties defaulted, where as `pageable.withSorts(s)` is not a static method and it creates a new instance by copying all other values from the existing instance, applying the requested sort criteria to that.  The same is the case for the other `with` methods as well (and also before/afterKeyset).  I don't know if  it matters to make a distinction in naming between the two patterns or if they are close enough to use the same style of naming, but was pointing this out in case it does matter.
