### ISSUE TITLE
Standard Exception Hierarchy?

### ISSUE THREAD

**Issue by graemerocher** [jakartaee/data#71]
**Description**

Currently the exception hierarchy is limited to `DataException`. One of the big value items of Spring/Micronaut Data is a standard access hierarchy for data access failures. In Spring this is:

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/dao/package-frame.html

In Micronaut this is less comprehensive but found here:

https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/exceptions/package-summary.html

The value here is that as a user regardless of the underlying database you get a consistent set of exceptions to catch and recover from.

This standard may be an opportunity to standardize this hierarchy.

//cc @odrotbohm

**Comment by otaviojava** [comment]
We put some exceptions to start, if we need more we can open this issue again.
