### ISSUE TITLE
[Release]: 1.0.0 GA

### ISSUE THREAD

**Issue by KyleAure** [jakartaee/data#713]
### Proposal

🎉  Let's start working on our GA release!  

### Outstanding work

RC1 was just released.
We should be be making very minimal changes at this point to ensure implementations using RC1 are not broken by the GA release.

- [x] https://github.com/jakartaee/data/pull/725
- [x] https://github.com/jakartaee/data/issues/722
- [x] https://github.com/jakartaee/data/issues/729
- [x] https://github.com/jakartaee/data/issues/732

### Certification Requests

- [x] https://github.com/jakartaee/data/issues/714

#### Prepare
  - [X] Open this issue.
  - [x] Complete outstanding work
  - [x] [Update TCK Signatures to capture API changes](https://github.com/jakartaee/data/actions/workflows/update.yml)
#### Stage release
  - [ ] [Update the CHANGELOG.adoc file to reflect the changes put into the new release](https://github.com/jakartaee/data/blob/main/CHANGELOG.adoc)
  - [x] [Build and stage artifacts to staging repository](https://ci.eclipse.org/data/view/Release%20Builds/job/jakarta-data-build-and-stage/)
  - [x] [Build and stage the TCK distribution artifact to download.eclipse.org](https://ci.eclipse.org/data/view/Eclipse%20Builds/job/jakarta-data-tck-build-and-stage/)
  - [x] Update this issue with a comment that links to the staged artifacts and the generated GitHub branch and tag
  - [x] [Create a `draft` release on GitHub](https://github.com/jakartaee/data/releases/new)
#### Verify and modify
  - [x] Ask for feedback from the community to verify the staged artifact has all the expected changes.
  - [x] If anything needs to be added before publishing do that now and repeat the `Stage Release` section
#### Publish release
  - [ ] [Publish staged artifacts to the public repository](https://ci.eclipse.org/data/view/Release%20Builds/job/jakarta-data-stage-to-release/)
  - [ ] [Publish staged TCK distribution artifact to download.eclipse.org](https://ci.eclipse.org/data/view/Eclipse%20Builds/job/jakarta-data-tck-staged-to-promoted/)
  - [ ] Update this issue with a comment that links to the published artifacts and the generated GitHub branch and tag
  - [ ] [Modify the `draft` release on GitHub to be `pre-release` or `latest`](https://github.com/jakartaee/data/releases)
#### Follow up
  - [ ] [Email a Jakarta steering committee member to promote the TCK Distribution publically](https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/)
  - [ ] Update versions in non-build files, such as:
    Documentation:
    - [README.adoc](https://github.com/jakartaee/data/blob/main/README.adoc)
    - [data-tck-reference-guide.adoc](https://github.com/jakartaee/data/blob/main/tck-dist/src/main/asciidoc/data-tck-reference-guide.adoc)

**Comment by KyleAure** [comment]
1.0.0 GA is staged: 

- GitHub Tag: [1.0.0](https://github.com/jakartaee/data/tree/1.0.0)
- GitHub Branch: [RELEASE-1.0.0](https://github.com/jakartaee/data/tree/RELEASE-1.0.0)
- GitHub Release DRAFT: [1.0.0](https://github.com/jakartaee/data/releases/edit/untagged-70ec785769b73726519b)
- Staging Repo: [jakartadata-1022](https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1022/)

**Comment by KyleAure** [comment]
Still working on getting the TCK distribution artifact staged on download.eclipse.org

**Comment by KyleAure** [comment]
Jakarta Data TCK Distribution is staged: https://download.eclipse.org/ee4j/data/jakartaee11/staged/eftl/

**Comment by KyleAure** [comment]
## 1.0.0 GA is Re-staged

- GitHub Tag: [1.0.0](https://github.com/jakartaee/data/tree/1.0.0)
- GitHub Branch: [RELEASE-1.0.0](https://github.com/jakartaee/data/tree/RELEASE-1.0.0)
- GitHub Release DRAFT: [1.0.0](https://github.com/jakartaee/data/releases/edit/untagged-0c08e51ac2a660e1beea)
- Staging Repo: [jakartadata-1023](https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1023/)
- Staged TCK Dist: [data-tck-1.0.0.zip](https://download.eclipse.org/ee4j/data/jakartaee11/staged/eftl/)

## Verification Data

| file | sha256 |
| -------- | ----- |
| [data-tck-1.0.0.zip](https://www.eclipse.org/downloads/download.php?file=/ee4j/data/jakartaee11/staged/eftl/data-tck-1.0.0.zip)  |cf7f4880def53b1bfbef71fb743e6f2dfa3f8b3f3af2b58021d03b2235f6739b |

**Comment by KyleAure** [comment]
## 1.0.0 GA is Re-staged

- GitHub Tag: [1.0.0](https://github.com/jakartaee/data/tree/1.0.0)
- GitHub Branch: [RELEASE-1.0.0](https://github.com/jakartaee/data/tree/RELEASE-1.0.0)
- GitHub Release DRAFT: [1.0.0](https://github.com/jakartaee/data/releases/edit/untagged-79dbb0a69ae40e4a9838)
- Staging Repo: [jakartadata-1024](https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1024/)
- Staged TCK Dist: [data-tck-1.0.0.zip](https://download.eclipse.org/ee4j/data/jakartaee11/staged/eftl/)

## Verification Data

| file | sha256 |
| -------- | ----- |
| [data-tck-1.0.0.zip](https://www.eclipse.org/downloads/download.php?file=/ee4j/data/jakartaee11/staged/eftl/data-tck-1.0.0.zip)  | 02dda1984b67f57bf6996942bea6b1234476e7d1a14bd5770f54f1264decaf35 |

**Comment by KyleAure** [comment]
## 1.0.0 GA is published

- GitHub Tag: [1.0.0](https://github.com/jakartaee/data/tree/1.0.0)
- GitHub Branch: [RELEASE-1.0.0](https://github.com/jakartaee/data/tree/RELEASE-1.0.0)
- GitHub Release: [1.0.0](https://github.com/jakartaee/data/releases/tag/1.0.0)
- Maven Central: [jakarta-data.api](https://repo1.maven.org/maven2/jakarta/data/jakarta.data-api/)
- Published TCK Dist: [data-tck-1.0.0.zip](https://download.eclipse.org/jakartaee/data/1.0/)

## Verification Data

| file | sha256 |
| -------- | ----- |
| [data-tck-1.0.0.zip](https://download.eclipse.org/jakartaee/data/1.0/data-tck-1.0.0.zip)  | 02dda1984b67f57bf6996942bea6b1234476e7d1a14bd5770f54f1264decaf35 |

**Comment by gavinking** [comment]
Fantastic!
