### ISSUE TITLE
[Certification]: Hibernate 6.6.0.X Jakarta Data 1.0

### ISSUE THREAD

**Issue by starksm64** [jakartaee/data#714]
### Organization

Red Hat

### Implementation

HIbernate ORM 6.6.0.Alpha1
https://hibernate.org/orm/releases/6.6/

### Specification

Jakarta Data 1.0

### Technology Compatibility Kit (TCK)

Jakarta Data 1.0.0 TCK
https://download.eclipse.org/ee4j/data/jakartaee11/staged/eftl/

### Technology Compatibility Kit (TCK) Validation

starksm@Scotts-Mac-Studio /tmp % shasum -a256 data-tck-1.0.0.zip 
02dda1984b67f57bf6996942bea6b1234476e7d1a14bd5770f54f1264decaf35  data-tck-1.0.0.zip

### Technology Compatibility Kit (TCK) Results

https://github.com/jakartaredhat/hibernate-data-tck/wiki/JD_100_TCK_Results

### Additional Specification Requirements

None

### Java Runtime(s)

openjdk version "17.0.4.1" 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode

openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode)

### Environments

starksm@Scotts-Mac-Studio arq % uname -a
Darwin Scotts-Mac-Studio.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Feb 19 20:25:23 PST 2024; root:xnu-8020.240.18.707.4~1/RELEASE_ARM64_T6000 arm64

### Eclipse Foundation Technology Compatibility Kit License (EFTL)

- [X] By checking this box I acknowledge that the organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php)

### TCK Requirements and Compatibility

- [X] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by starksm64** [comment]
@KyleAure @njr-11 This has been updated for the staged release of the 1.0.0 TCK

**Comment by KyleAure** [comment]
Closing as approved by lazy consensus
