### ISSUE TITLE
[Bug]: ANTLR Lexer Fails to Recognize Identifiers Correctly in JDQL Queries

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#717]
### Specification Version

1.0.0-RC1

### Bug report

When attempting to parse JDQL queries using an ANTLR-generated lexer, token recognition errors occur for each character in certain identifiers, such as "entity". The lexer does not recognize "entity" as a single valid identifier but reports errors for each individual character.

#### Steps to Reproduce

1. **Generate Lexer and Parser**:
   - Use ANTLR to generate code from the JDQL grammar available at [JDQL Grammar File](https://github.com/jakartaee/data/blob/main/spec/src/antlr/JDQL.g4).

2. **Write a Test to Parse the Query**:

   - Implement a test in Java to parse the query "FROM entity" using the generated lexer. The expected behavior is for the lexer to tokenize the input into recognizable tokens for `FROM` and `entity`.

3. **Run the Test**:
   - Execute the test using the following JUnit 5 setup:
     ```java
     import org.antlr.v4.runtime.*;
     import org.antlr.v4.runtime.tree.*;
     import org.junit.jupiter.params.ParameterizedTest;
     import org.junit.jupiter.params.provider.ValueSource;

     public class JDQLLexerTest {
         @ParameterizedTest(name = "Should parse the query {0}")
         @ValueSource(strings = {"FROM entity"})
         void shouldReturnParserQuery(String query) {
             CharStream stream = CharStreams.fromString(query);
             JDQLLexer lexer = new JDQLLexer(stream);
             CommonTokenStream tokens = new CommonTokenStream(lexer);
             tokens.fill();
             for (Token token : tokens.getTokens()) {
                 System.out.println(token.getText() + " : " + token.getType());
             }
         }
     }
     ```
   - The output logs display token recognition errors at each character:
     ```
     line 1:4 token recognition error at: ' '
     line 1:5 token recognition error at: 'e'
     line 1:6 token recognition error at: 'n'
     line 1:7 token recognition error at: 't'
     line 1:8 token recognition error at: 'i'
     line 1:9 token recognition error at: 't'
     line 1:10 token recognition error at: 'y'
     ```

#### Suspected Issue
It appears there may be a misconfiguration in the lexer rules or an issue with how the lexer handles whitespace and identifiers. Here's a potential missing configuration that might resolve the issue:
```antlr
IDENTIFIER : [a-zA-Z_][a-zA-Z0-9_]* ;
WS : [ \t\r\n]+ -> skip ;
```
Including the above rules in the `JDQL.g4` file should instruct the lexer to correctly recognize identifiers and skip whitespace, which may resolve the parsing errors.

#### Request for Assistance

I'm unsure if additional configurations are missing or if there are other steps required to correctly set up the JDQL lexer. Any guidance or suggestions on how to properly configure the lexer or adjust the grammar file would be greatly appreciated.

**Comment by gavinking** [comment]
@otaviojava The grammar in the spec is a parser grammar: it does not include any rules for lexical analysis, which are usually specified in a separate grammar. The lexical structure of JDQL is defined in section 5.2 of the specification, and it's straightforward to turn that specification into a grammar for an ANTLR lever. The parser grammar would then reuse the token types from the lexer.

[Also note that the grammar as provided contains an ambiguity noted in a comment, so probably requires some 
"massaging" since that ambiguity must be resolved semantically.]

**Comment by otaviojava** [comment]
Thanks.
