### ISSUE TITLE
Why is Pageable just CursorPageable? [VOTE]

### ISSUE THREAD

**Issue by keilw** [jakartaee/data#72]
**Description**

Looking at this [Pageable](https://github.com/jakartaee/data/blob/main/api/src/main/java/jakarta/data/repository/Pageable.java)
compared to [Micronaut](https://micronaut-projects.github.io/micronaut-data/1.1.2/api/index.html?io/micronaut/data/model/Pageable.html)
and [Spring Data](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Pageable.html)

There is no point in separating `Pageable` and `KeySetPageable`, because the "abstract" class/interface does no abstraction at all, it just deals with `KeySetPageable` and its `Cursor` anyway.
All this API supports is [cursor-based pagination](https://engage.so/blog/a-deep-dive-into-offset-and-cursor-based-pagination-in-mongodb/#what-is-cursor-based-pagination)
While Spring Data and Micronaut (without 3rd party extensions) both rely on
[offset-based pagination](https://engage.so/blog/a-deep-dive-into-offset-and-cursor-based-pagination-in-mongodb/#what-is-offset-based-pagination).

@graemerocher, @odrotbohm Was the offset-based pagination so far practiced in Micronaut or Spring Data a mistake and you would like to force its current users to switch all apps to cursor now, or why is there no offset `Pageable` here yet?
If both can be supported I would have imagined an abstract base `Pageable` with just the page number, size and (unless #54 gets them separated) sorts, but keeping all the `KeySet` stuff in `KeySetPageable`.
Then another (frankly the names would be a bit confusing, hence `CursorPageable` would sound clearer?) `OffsetPageable` class or interface (or record ;-)

That's how `Collection` works, it is inherited by specialized sub-interfaces like `List`, `Queue` or `Set`, but any factory methods like `of()` are in the subsequent subtypes.

Why was this concept broken here?

**Comment by graemerocher** [comment]
offset based pagination is just more commonly used and understood and more easily made into a generic API, we looked at keyset pagination but were unsure how to make it generic so left it up to users to implement

**Comment by njr-11** [comment]
Thanks for bringing up this topic.  Originally, when we thought of `KeysetPageable` its purpose was to be the way in which the user indicates that keyset cursor-based pagination is wanted for a repository method.  Later on, we came up with a different way of indicating this: the KeysetAwarePage/Slice return type of the repository method.  Given that `KeysetPageable` is no longer used for that purpose, and the only difference between `Pageable` and `KeysetPageable` is that the latter adds on a cursor with a direction, it would be possible to simplify things by not having `KeysetPageable` at all, and just use a single `Pageable` interface to cover both offset and cursor pagination.  The default `mode` of a `Pageable` (no keyset cursor) would be `OFFSET`, and when there is a cursor, then the mode would be `CURSOR_NEXT` or `CURSOR_PREVIOUS`.  This would make the usage patterns for both forms of pagination be more similar for the end user, and it would also reflect the possibility of using the two in combination.  A user can request the first page with offset pagination and then use keyset pagination from there to get the next or previous page reducing the risk of misses and duplicates when traversing pages.

**Comment by otaviojava** [comment]
Once we have two PRs merged, I'll close this one.
