### ISSUE TITLE
[clarification]: Clarification on Case Sensitivity for Keywords in ANTLR Grammar for Jakarta Data Specification

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#734]
### Specification

https://github.com/jakartaee/data/blob/main/spec/src/antlr/JDQL.g4

### I need clarification on ...

Please clarify how the Jakarta Data specification intends to handle case sensitivity for Query keywords in the ANTLR grammar. 

Specifically, should the grammar support uppercase and lowercase keywords such as SELECT, UPDATE, and DELETE?

Another question: should the select be a constant instead of the quote:

```
select_clause : SELECT select_list;
```

```
select_clause : SELECT select_list;
// Token rules
SELECT          : 'SELECT' | 'select';
```

If we intend to allow both "SELECT" and "select" (or any other variations), then using 'SELECT' directly in your rules can be considered a bug because it restricts the input to only one case.

**Comment by gavinking** [comment]
Section 5.2.1 says:

> Identifiers are case-sensitive

> Keywords and other reserved identifiers are case- insensitive

I think that covers it, no?

**Comment by otaviojava** [comment]
you are right
