### ISSUE TITLE
[Certification]: Compatibility certification request for Open Liberty 24.0.0.6-beta for Jakarta Data 1.0 (of Jakarta EE 11)

### ISSUE THREAD

**Issue by brideck** [jakartaee/data#741]
### Organization

[IBM](https://www.ibm.com/)

### Implementation

[Open Liberty 24.0.0.6-beta](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/tck/2024-05-06_1951/openliberty-24.0.0.6-beta.zip)

### Specification

[Jakarta Data 1.0](https://jakarta.ee/specifications/data/1.0/)

### Technology Compatibility Kit (TCK)

[Jakarta Data 1.0 TCK](https://download.eclipse.org/ee4j/data/jakartaee11/staged/eftl/data-tck-1.0.0.zip) | [SHA](https://download.eclipse.org/ee4j/data/jakartaee11/staged/eftl/data-tck-1.0.0.info)

### Technology Compatibility Kit (TCK) Validation

`02dda1984b67f57bf6996942bea6b1234476e7d1a14bd5770f54f1264decaf35`

### Technology Compatibility Kit (TCK) Results

https://openliberty.io/certifications/jakartaee/11/data/24.0.0.6-beta-Java17-TCKResults.html
https://openliberty.io/certifications/jakartaee/11/data/24.0.0.6-beta-Java21-TCKResults.html

### Additional Specification Requirements

[Instructions to run the TCK with Open Liberty](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.jakarta.data.1.0_fat_tck)

### Java Runtime(s)

Java 17 and Java 21:

```
java version "17.0.4.1" 2022-08-12
IBM Semeru Runtime Certified Edition 17.0.4.1 (build 17.0.4.1+1)
Eclipse OpenJ9 VM 17.0.4.1 (build openj9-0.33.1, JRE 17 Linux amd64-64-Bit Compressed References 20220812_206 (JIT enabled, AOT enabled)
OpenJ9   - 1d9d16830
OMR      - b58aa2708
JCL      - df9b7169bff based on jdk-17.0.4.1+1)

openjdk version "21.0.2" 2024-01-16 LTS
IBM Semeru Runtime Open Edition 21.0.2.0 (build 21.0.2+13-LTS)
Eclipse OpenJ9 VM 21.0.2.0 (build openj9-0.43.0, JRE 21 Linux amd64-64-Bit Compressed References 20240116_94 (JIT enabled, AOT enabled)
OpenJ9   - 2c3d78b48
OMR      - ea8124dbc
JCL      - 78c4500a434 based on jdk-21.0.2+13)
```

### Environments

Ubuntu (5.15.0-107-generic)

### Eclipse Foundation Technology Compatibility Kit License (EFTL)

- [X] By checking this box I acknowledge that the organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php)

### TCK Requirements and Compatibility

- [X] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by KyleAure** [comment]
Closing as approved by lazy consensus

**Comment by njr-11** [comment]
> Hi This must work with the latest open liberty beta(25.0.0-2-beta) right? Is there any working example? I am not getting mine to work.

Yes, Open Liberty has a good amount of automated testing for Data that runs with each build to ensure it doesn't get broken. It is definitely working in that version.  One simple example project is here,
https://github.com/OpenLiberty/sample-jakarta-data

It should be noted that some configuration will be required, like enabling the `data-1.0` feature and configuring a data source to get it to connect to your database. You might also want to check for any errors in the logs.

**Comment by lulseged** [comment]
Hi

Yes I have <feature>data-1.0 </feature> and dataSource in my server.xml.

I have already checked sample-jakarta-data.

Nothing is logged as error or trace.

Open liberty has started without any errors, meaning there is implemenation that satsfys @Repository.

Method in the repostory interfcae is called but nothing happens.

I will check it again.

BR
Lulseged

________________________________

**Comment by njr-11** [comment]
> Method in the repostory interfcae is called but nothing happens.

I would recommend opening an [issue against the Open Liberty github project](https://github.com/OpenLiberty/open-liberty/issues/new) with a more detailed description of the scenario, including the repository interface you are using, the entity class, and the code where you are using it, along with clarification of what you mean by nothing happens. For example, you invoke the method and it completes but you don't see any updates in your database.  Or it doesn't return any results.  Or flow of control never returns to your application at all.

**Comment by lulseged** [comment]
The only difference I have with the sample-jakarta-data is that I have ear maven project and not war project.
It is not even trying to start, nothing in the logs.

**Comment by njr-11** [comment]
@lulseged Did you open an [issue against the Open Liberty github project](https://github.com/OpenLiberty/open-liberty/issues/new) for this?  The specification repository is not the right place for debugging and investigating product issues.  If you open the issue, someone from the team working on the feature should be able to look into either fixing it or confirming if it has already been fixed in more recent code.

**Comment by lulseged** [comment]
Yes, now I have opened issue on open liberty.
Thanks
