### ISSUE TITLE
[Release]: 1.0.1 Service Release

### ISSUE THREAD

**Issue by KyleAure** [jakartaee/data#762]
### Proposal

During the release review process some issues were brought up that will require us to do an immediate service release.

### Outstanding work

- [x] https://github.com/jakartaee/data/issues/746
- [x] https://github.com/jakartaee/data/pull/761
- [x] https://github.com/jakartaee/data/pull/747
- [x] https://github.com/jakartaee/data/pull/745
- [x] https://github.com/jakartaee/data/pull/738
- [x] https://github.com/jakartaee/data/issues/764
- [x] Verify with JNoSQL if there are any other changes/challenges that need to be resolved with the Jakarta Data TCK
  - [x] https://github.com/jakartaee/data/issues/768 

#### Prepare
  - [X] Open this issue.
  - [x] Complete outstanding work
  - [x] [Update TCK Signatures to capture API changes](https://github.com/jakartaee/data/actions/workflows/update.yml)
#### Stage release
  - [x] [Update the CHANGELOG.adoc file to reflect the changes put into the new release](https://github.com/jakartaee/data/blob/main/CHANGELOG.adoc)
  - [x] [Build and stage artifacts to staging repository](https://ci.eclipse.org/data/view/Release%20Builds/job/jakarta-data-build-and-stage/)
  - [x] [Build and stage the TCK distribution artifact to download.eclipse.org](https://ci.eclipse.org/data/view/Eclipse%20Builds/job/jakarta-data-tck-build-and-stage/)
  - [x] Update this issue with a comment that links to the staged artifacts and the generated GitHub branch and tag
  - [x] [Create a `draft` release on GitHub](https://github.com/jakartaee/data/releases/new)
#### Verify and modify
  - [x] Ask for feedback from the community to verify the staged artifact has all the expected changes.
  - [x] If anything needs to be added before publishing do that now and repeat the `Stage Release` section
#### Publish release
  - [x] [Publish staged artifacts to the public repository](https://ci.eclipse.org/data/view/Release%20Builds/job/jakarta-data-stage-to-release/)
  - [x] [Publish staged TCK distribution artifact to download.eclipse.org](https://ci.eclipse.org/data/view/Eclipse%20Builds/job/jakarta-data-tck-staged-to-promoted/)
  - [x] Update this issue with a comment that links to the published artifacts and the generated GitHub branch and tag
  - [x] [Modify the `draft` release on GitHub to be `pre-release` or `latest`](https://github.com/jakartaee/data/releases)
#### Follow up
  - [x] [Email a Jakarta steering committee member to promote the TCK Distribution publically](https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/)
  - [x] [Create pull request to https://github.com/jakartaee/specifications](https://github.com/jakartaee/specifications/blob/master/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md)
    - upload [generated specification documentation](https://github.com/jakartaee/data/actions/workflows/specification.yml)
  - [x] Update versions in non-build files, such as:
    Documentation:
    - [README.adoc](https://github.com/jakartaee/data/blob/main/README.adoc)
    - [data-tck-reference-guide.adoc](https://github.com/jakartaee/data/blob/main/tck-dist/src/main/asciidoc/data-tck-reference-guide.adoc)

**Comment by KyleAure** [comment]
## 1.0.1 is staged

- GitHub Tag: [1.0.1](https://github.com/jakartaee/data/tree/1.0.1)
- GitHub Branch: [RELEASE-1.0.1](https://github.com/jakartaee/data/tree/RELEASE-1.0.1)
- GitHub Release DRAFT: [1.0.1](https://github.com/jakartaee/data/releases/edit/untagged-af2aee56ccc749ff81a1)
- Staging Repo: [jakartadata-1024](https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1024/)
- Staged TCK Dist: [data-tck-1.0.1.zip](https://download.eclipse.org/ee4j/data/jakartaee11/staged/eftl/)

## Verification Data

| file | sha256 |
| -------- | ----- |
| [data-tck-1.0.1.zip](https://www.eclipse.org/downloads/download.php?file=/ee4j/data/jakartaee11/staged/eftl/data-tck-1.0.1.zip)  | 9f3c74d4ebe3116501520a19851214eb87d1e671056829e95696cf1e263a187a |

**Comment by KyleAure** [comment]
## 1.0.1 is re-staged

- GitHub Tag: [1.0.1](https://github.com/jakartaee/data/tree/1.0.1)
- GitHub Branch: [RELEASE-1.0.1](https://github.com/jakartaee/data/tree/RELEASE-1.0.1)
- GitHub Release DRAFT: [1.0.1](https://github.com/jakartaee/data/releases/edit/untagged-a80cc4916906a1b6b423)
- Staging Repo: [jakartadata-1026](https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1026/)
- Staged TCK Dist: [data-tck-1.0.1.zip](https://download.eclipse.org/ee4j/data/jakartaee11/staged/eftl/)

## Verification Data

| file | sha256 |
| -------- | ----- |
| [data-tck-1.0.1.zip](https://www.eclipse.org/downloads/download.php?file=/ee4j/data/jakartaee11/staged/eftl/data-tck-1.0.1.zip)  | 20d3e77db8a6335472fb153b370c5ea7ab876e727b858472153b8bf274a2b6dc |

FYI @otaviojava

**Comment by KyleAure** [comment]
## 1.0.1 is re-staged

- GitHub Tag: [1.0.1](https://github.com/jakartaee/data/tree/1.0.1)
- GitHub Branch: [RELEASE-1.0.1](https://github.com/jakartaee/data/tree/RELEASE-1.0.1)
- GitHub Release DRAFT: [1.0.1](https://github.com/jakartaee/data/releases/edit/untagged-71e552c17972da557877)
- Staging Repo: [jakartadata-1027](https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1027/)
- Staged TCK Dist: [data-tck-1.0.1.zip](https://download.eclipse.org/ee4j/data/jakartaee11/staged/eftl/)

## Verification Data

| file | sha256 |
| -------- | ----- |
| [data-tck-1.0.1.zip](https://www.eclipse.org/downloads/download.php?file=/ee4j/data/jakartaee11/staged/eftl/data-tck-1.0.1.zip)  | 92babb604b4e346f8d19929979c1d6aaf013fdf990b5e97bdd95502ad7db5b4c |

FYI @otaviojava @njr-11 @gavinking 
I will test the new staged TCK against Open Liberty.
Let me know if you are satisfied with this service release and I can work on getting it published/promoted.

**Comment by KyleAure** [comment]
@otaviojava - Just following up.  Have you been able to run with this new staged version?  If everything is good on your side let me know and I can publish 1.0.1.

**Comment by otaviojava** [comment]
> @otaviojava - Just following up. Have you been able to run with this new staged version? If everything is good on your side let me know and I can publish 1.0.1.

Please, let me test it today; I will bring an update tomorrow morning.

**Comment by otaviojava** [comment]
@keilw 

While the 1.0.1-SNAPSHOT is working.
```
[INFO] Tests run: 73, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.456 s - in org.eclipse.jnosql.tck.MyEntityTests
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 74, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
```

The version 1.0.1 is not, could you check if it is missing some code?

```
[ERROR]   MyEntityTests>EntityTests.testUpdateQueryWithoutWhereClause:2115 » UnsupportedOperation The return type must be Void when the query is not a SELECT operation, due to the nature of DELETE and UPDATE operations. The query: DELETE FROM Box
[INFO] 
[ERROR] Tests run: 74, Failures: 5, Errors: 9, Skipped: 0
```

**Comment by KyleAure** [comment]
@otaviojava how are you pulling the 1.0.1 TCK? 
https://jakarta.oss.sonatype.org/content/repositories/staging/ -> 1.0.1 was uploaded Jul 03
https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1027/ -> 1.0.1 was uploaded Sep 19

I think this is a quark with how the staging sonatype repository is setup.  The staging repository has the first version ever uploaded, when re-staging you have to go directly to temporary repository.

**Comment by otaviojava** [comment]
> @otaviojava how are you pulling the 1.0.1 TCK? https://jakarta.oss.sonatype.org/content/repositories/staging/ -> 1.0.1 was uploaded Jul 03 https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1027/ -> 1.0.1 was uploaded Sep 19
> 
> I think there may have been an issue with our Jenkins build. I looked back at the output and see:
> 
> ```
> -[ Drop old staging repository deployments ]------------------------------------
> Sep 19, 2024 3:26:48 PM com.sun.jersey.api.client.ClientResponse getEntity
> SEVERE: A message body reader for Java class com.sonatype.nexus.staging.api.dto.StagingRuleFailuresDTO, and Java type class com.sonatype.nexus.staging.api.dto.StagingRuleFailuresDTO, and MIME media type text/html was not found
> Sep 19, 2024 3:26:48 PM com.sun.jersey.api.client.ClientResponse getEntity
> ```
> 
> I think the previous version was never deleted. I'll look into it

I downloaded it from Maven.

**Comment by KyleAure** [comment]
Can you try using the version uploaded to [jakarta.oss.sonatype.org/content/repositories/jakartadata-1027](https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1027/)

**Comment by KyleAure** [comment]
I think the issue was likely on the sonatype server side.  I just did a dry-run of the jenkins build and it was able to get a list of old repositories to drop: 

```
-[ Drop old staging repository deployments ]------------------------------------
Repository ID: jakartadata-1026
Repository ID: jakartadata-1027
```

I could re-stage this again, or just continue forward with using [jakarta.oss.sonatype.org/content/repositories/jakartadata-1027](https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1027/) which is what all our build automation is based on.

**Comment by otaviojava** [comment]
Hey @KyleAure, how can I do this?

I am removing, manually, the version, but it is still with the version of July.

![Screenshot 2024-09-30 at 08 34 24](https://github.com/user-attachments/assets/d03b908d-19a8-4290-9c2e-b41635431879)

**Comment by KyleAure** [comment]
@otaviojava Update your pom.xml to use 
```xml
<repositories>
  <repository>
    <id>sonatype-nexus-staging</id>
    <name>Sonatype Nexus Staging</name>
    <url>https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1027/</url>
    <releases>
      <enabled>true</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
</repositories>
```

**Comment by KyleAure** [comment]
## 1.0.1 Service Release is published

- GitHub Tag: [1.0.1](https://github.com/jakartaee/data/tree/1.0.1)
- GitHub Branch: [RELEASE-1.0.1](https://github.com/jakartaee/data/tree/RELEASE-1.0.1)
- GitHub Release: [1.0.1](https://github.com/jakartaee/data/releases/tag/1.0.1)
- Maven Central: [jakarta-data.api](https://repo1.maven.org/maven2/jakarta/data/jakarta.data-api/)
- Promoted TCK Dist: [data-tck-1.0.1.zip](https://www.eclipse.org/downloads/download.php?file=/ee4j/data/jakartaee11/promoted/eftl/data-tck-1.0.1.zip)

## Verification Data

| file | sha256 |
| -------- | ----- |
| [data-tck-1.0.1.zip](https://www.eclipse.org/downloads/download.php?file=/ee4j/data/jakartaee11/promoted/eftl/data-tck-1.0.1.zip)  | 92babb604b4e346f8d19929979c1d6aaf013fdf990b5e97bdd95502ad7db5b4c |
