### ISSUE TITLE
[clarification]: IgnoreCase should be optional, but it is mandatory by TCK.

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#781]
### Specification

https://github.com/jakartaee/data/blob/main/spec/src/main/asciidoc/method-query.asciidoc

### I need clarification on ...

> An implementation of Query by Method Name backed by a document or graph database is not required to support Contains, EndsWith, StartsWith, Like, IgnoreCase, In, or Null. A repository method must raise java.lang.UnsupportedOperationException or a more specific subclass of the exception if the database does not provide the requested functionality.

Method:
- testSingleEntity

**Comment by njr-11** [comment]
I'll switch this from `question` to TCK test bug and look into updating the test(s).
