### ISSUE TITLE
Provider model for plugging in third-party Jakarta Data providers

### ISSUE THREAD

**Issue by njr-11** [jakartaee/data#80]
**Description**

As a:

- [x] Application user/user of the configuration itself
- [ ] API user (application developer)
- [ ] SPI user (container or runtime developer)
- [ ] Specification implementer

...I need to be able to:

use a Jakarta EE product with one or more third-party Jakarta Data providers

...which enables me to:

connect to both Relational databases as well as Column, Document, Graph, and Key-Value (NoSQL) databases in my application(s) via the repository pattern that is defined by Jakarta Data.

This issue is for standardizing a provider model that a Jakarta EE product (such as web or core profile) can use to integrate with third-party providers of Jakarta Data.  This issue will not attempt to deal with configuration, which is also important but is not being designed under this issue.

**Comment by otaviojava** [comment]
IMHO: we should keep this option for each vendor.

E.g., there are more than four types that Jakarta NoSQL support, such as time series. Furthermore, we have solutions such as Microstream or rest applications.

**Comment by njr-11** [comment]
This was done with CDI extensions instead.
