### ISSUE TITLE
Simplify unit test display names

### ISSUE THREAD

**Issue by KyleAure** [jakartaee/data#82]
Many of the unit tests for the API use a display name that matches the method name like in this example: 

https://github.com/jakartaee/data/blob/26033992c9955190f77bda319a6a2c7ef5958101/api/src/test/java/jakarta/data/repository/PageableTest.java#L44-L53

Instead, we could use the `@DisplayNameGeneration` annotation on the class to automatically give tests displays names based on the test method name. 

For example:
```java
@DisplayNameGeneration(ReplaceCamelCase.class)
class LimitTest {
    @Test
    void shouldReturnErrorWhen_maxResults_IsNegative() {
      ...
    }
    @Test
    void shouldCreateLimitWithRange() {
      ...
    }
}
```

This would result in display names of: 
```txt
- Should return error when maxResults is negative
- Should create limit with range
```

**Comment by FanJups** [comment]
Good idea, I will work on it.

**Comment by KyleAure** [comment]
Closing not appropriate for this project to handle.

**Comment by FanJups** [comment]
I just opened a new JUnit issue to handle this case https://github.com/junit-team/junit5/issues/3569

**Comment by FanJups** [comment]
JUnit Pioneer plans to integrate this feature but they are waiting the decision of JUnit

https://github.com/junit-pioneer/junit-pioneer/issues/793

**Comment by FanJups** [comment]
This feature will be implemented by JUnit Pioneer https://github.com/junit-pioneer/junit-pioneer/pull/819

**Comment by FanJups** [comment]
Its done junit-pioneer v2.3.0 https://github.com/junit-pioneer/junit-pioneer/pull/819 💯
