### ISSUE TITLE
Should we define Entity and Repository annotation as Stereotype?

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/data#91]
To make a bean recovery on CDI, we have several conditions on the [spec](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#bean_defining_annotations)

Otherwise, we need to set all the implementations with [bean-recovery=all](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#bean_archive)

Is that ok to put `Stereotype` on those annotations?

It will work pretty similarly to [RegisterRestClient](https://github.com/eclipse/microprofile-rest-client/blob/master/api/src/main/java/org/eclipse/microprofile/rest/client/inject/RegisterRestClient.java)

So:

```java
@Stereotype
@Dependent
public @interface Repository {
}

@Stereotype
@Dependent
public @interface Entity {
}

```

:warning: This change will require CDI annotation `provided` [dependency](https://mvnrepository.com/artifact/jakarta.enterprise/jakarta.enterprise.cdi-api/4.0.1)

Ref: [CDI Spec](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#bean_defining_annotations)

**Comment by otaviojava** [comment]
It would be an impact to do that from Spring and Micronaut?

@graemerocher @njr-11@mp911de @Emily-Jiang

**Comment by graemerocher** [comment]
No, mandating CDI annotations shouldn't be a requirement

**Comment by otaviojava** [comment]
Thank you, I will update this issue with won't fix.
